name = "siftersearch"
main = "build/index.js"
compatibility_date = "2023-12-01"

# D1 database configuration
[[d1_databases]]
binding = "DB"
database_name = "siftersearch"
database_id = "8ba77a73-ef89-4d28-aef5-1796db92aa87"

# Local development configuration
[env.local]
[[env.local.d1_databases]]
binding = "DB"
database_name = "siftersearch-local"
database_id = "da8e3ead-8032-446c-ab15-a23315a1ebec"

# R2 bucket configuration with structured prefixes
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "siftersearch"
preview_bucket_name = "siftersearch-local"

# Environment variables
[vars]
STORAGE_PREFIX_MANTICORE_INDEXES = "manticore/indexes/"
STORAGE_PREFIX_MANTICORE_SNAPSHOTS = "manticore/snapshots/"
STORAGE_PREFIX_DOCUMENTS_ORIGINALS = "documents/originals/"
STORAGE_PREFIX_DOCUMENTS_GENERATED = "documents/generated/"
STORAGE_PREFIX_DOCUMENTS_GENERATED_PUBLIC = "documents/generated/public/"
STORAGE_PREFIX_DOCUMENTS_GENERATED_RESTRICTED = "documents/generated/restricted/"
STORAGE_PREFIX_BACKUPS = "backups/"
PUBLIC_R2_URL = "https://public.siftersearch.r2.dev"
