// Shared biography data layer — the single source of truth for person records (list + dossier) and source-book
// facets, used by BOTH the internal /api/graph/bio/* routes and the official /api/v1/people API.
import { queryAll, queryOne } from './db.js';
import { INTEGRATION_PHASES } from './integration-phases.js';
import { chatCompletion } from './ai.js';
import * as pipelineState from './pipeline/state.js';
import { reachedBound } from './pipeline/queue.js';   // the pipeline's OWN completion test → one definition of "done"
import { ADJUDICATOR_VERSION } from './rag/index.js';
import { DEFAULT_PEAK_WINDOWS, nowInPeak, peakEndsAt } from './pipeline/peak.js';
import fs from 'fs';
import path from 'path';

export const BIO_ROOT = path.join(process.env.HOME || '/home/chad', 'sifter', 'bio-assets');
export const readBioManifest = () => { try { return JSON.parse(fs.readFileSync(path.join(BIO_ROOT, 'manifest.json'), 'utf8')); } catch { return {}; } };

// Source books with full person-mention coverage today. Add the Pillars (Balyuzi 462/466/467/3887,
// Taherzadeh 429-432, Mázandarání 420/16564/12262/11322, Momen 11557) here as each is run through the
// entity pipeline — their filter facets light up automatically once they appear in entity_mentions.
export const SOURCE_BOOKS = [
  { key: 'gpb', label: 'God Passes By', docs: [21310, 57347] },
  { key: 'dawn-breakers', label: 'The Dawn-Breakers', docs: [21308] },
];

// entity_id → Set(book keys). Grounding comes from the DISAMBIGUATED evidence layer — an entity is "in" a book
// if it has a bound v2 mention OR a bound hard-claim there (both carry doc_id + entity_id directly, so no
// content-id join). The legacy NER entity_mentions table is retired: identity is now resolved by disambiguation
// + claim evidence, never by raw name-extraction.
export async function computeBookSources() {
  const bookOf = {};
  for (const b of SOURCE_BOOKS) {
    const ph = b.docs.map(() => '?').join(',');
    const ents = await queryAll(
      `SELECT DISTINCT entity_id FROM entity_mentions_v2 WHERE doc_id IN (${ph}) AND entity_id IS NOT NULL
       UNION SELECT DISTINCT entity_id FROM entity_claims WHERE doc_id IN (${ph}) AND entity_id IS NOT NULL`,
      [...b.docs, ...b.docs]);
    for (const e of ents) (bookOf[e.entity_id] ||= new Set()).add(b.key);
  }
  return bookOf;
}

// The classified Bahá'í history/biography catalog that fills the dynamic "histories" phase — generated by the
// content-sample classifier (scripts/classify-bahai-books.mjs), committed as data. Absence → empty phase.
const HISTORY_CATALOG_PATH = path.join(process.cwd(), 'api', 'lib', 'bahai-history-catalog.json');
const GENRE_RANK = { history: 0, biography: 1 }; // general histories front-loaded, then biographies
export function readHistoryCatalog() {
  try { return (JSON.parse(fs.readFileSync(HISTORY_CATALOG_PATH, 'utf8')).books || [])
    .filter(b => b && GENRE_RANK[b.genre] !== undefined); } catch { return []; }
}

// Live grounding state is reported by the executor (api/lib/pipeline/run-grounding.js) INTO doc_pipeline.run_json —
// the single source of truth (replaces the old data/siftersearch-grounding-status.json file). bio.js READS it; it
// never infers the active book from a file. `pipelineState.activeRun()` returns the freshest non-idle run, or null.
// The stages, in order — must match run-grounding.js GROUNDING_STAGES (drives the current book's % progress).
const GROUNDING_STAGES = ['disambiguate', 'mentions', 'claims', 'reconcile', 'research', 'project', 'link', 'merge', 'dedup', 'hype', 'verify'];
// Per-DOC cache (books ground in parallel, so a single-slot cache would thrash between them each poll).
const _activeCache = new Map();   // docId → { sig, at, value }

// Per-book stage job sizes (item counts) → the bar's per-stage weights. prose paras drive the paragraph passes
// (disambiguate/claims/hype); distinct mention-clusters drive reconcile (the big one on biography volumes);
// research ≈ a stable fraction of clusters (NOT the live 'uncertain' count, which grows during reconcile and
// would wobble the total). The quick bookkeeping stages get a small nominal so they contribute a sliver, never 0.
// Static per run → cached ~2min by doc (a GROUP BY over mentions is too heavy to run on every 3s poll).
const _sizeCache = new Map();
const _pctFloor = new Map();   // docId → {startedAt, pct}: per-run monotonic floor so emitted % never regresses
async function stageSizes(docId) {
  const hit = _sizeCache.get(docId);
  if (hit && Date.now() - hit.at < 120000) return hit.sizes;
  const prose = (await queryAll(`SELECT COUNT(*) n FROM content WHERE doc_id=? AND blocktype IN ('paragraph','quote') AND deleted_at IS NULL`, [docId]))[0]?.n || 0;
  const clusters = (await queryAll(`SELECT COUNT(DISTINCT resolved_as) n FROM entity_mentions_v2 WHERE doc_id=? AND resolved_as IS NOT NULL`, [docId]))[0]?.n || 0;
  const sizes = {
    disambiguate: prose, mentions: prose ? 30 : 0, claims: prose,
    reconcile: clusters, research: Math.round(clusters * 0.3),
    project: 30, link: 30, merge: 60, dedup: 30, hype: prose, verify: 20,
  };
  _sizeCache.set(docId, { sizes, at: Date.now() });
  return sizes;
}

/**
 * The live block for ONE grounding book. Takes the run (rather than fetching "the" run) so N books in flight
 * each get their own block — the API reports a LIST and the UI tabs between them.
 * `run` may be null: then the claim-write fallback below infers a book (legacy/transition runs).
 */
async function computeActiveBook(run, staticDocs, meta) {
  let docId = run?.doc_id ?? null, stage = run?.stage ?? null;
  let si = run?.stageIndex ?? null;
  const ts = run?.totalStages ?? GROUNDING_STAGES.length;
  const startedAt = run?.startedAt ?? null;
  // Lightweight: the active block is polled ~30s. Cache ~20s per doc, keyed by the run signature, so repeated
  // polls (and multiple viewers) don't re-run COUNTs against the live DB while grounding writes.
  const sig = run ? `${docId}:${stage}:${run.updatedAt}` : 'none';
  const hit = _activeCache.get(docId ?? 'none');
  if (hit && hit.sig === sig && Date.now() - hit.at < 20000) return hit.value;
  const remember = (value) => { _activeCache.set(docId ?? 'none', { sig, at: Date.now(), value }); return value; };
  // Fallback (transition / a run predating run_json): the curated book with the most RECENT claim write — but ONLY if
  // that write is <5min old (grounding genuinely live). Stale writes = nothing active, so idle shows no book.
  if (!docId && staticDocs.length) {
    const ph = staticDocs.map(() => '?').join(',');
    const row = (await queryAll(`SELECT doc_id d, MAX(asserted_at) m FROM entity_claims
        WHERE doc_id IN (${ph}) GROUP BY doc_id ORDER BY m DESC LIMIT 1`, staticDocs))[0];
    if (row?.d && row.m && Date.now() - new Date(row.m).getTime() < 5 * 60000) { docId = row.d; stage = 'grounding'; }
  }
  if (!docId) return remember(null);
  const claims = (await queryAll(`SELECT COUNT(*) n FROM entity_claims WHERE doc_id=?`, [docId]))[0]?.n || 0;
  // No live status file (older driver / prefetch): INFER how far the book has progressed from its DB artifacts
  // so the current book still shows a real progress bar — disambiguated → mentions → claims → bound (reconciled)
  // → HyPE. This is the "how far along" signal the popup exists to surface.
  if (si == null) {
    const one = async (sql) => (await queryAll(sql, [docId]))[0]?.n || 0;
    const bound = await one(`SELECT COUNT(*) n FROM entity_mentions_v2 WHERE doc_id=? AND entity_id IS NOT NULL`);
    const hype = await one(`SELECT COUNT(*) n FROM content WHERE doc_id=? AND hyp_questions IS NOT NULL`);
    const ment = await one(`SELECT COUNT(*) n FROM entity_mentions_v2 WHERE doc_id=?`);
    const at = (name) => GROUNDING_STAGES.indexOf(name);
    si = (hype > 0 && bound > 0) ? at('hype') : bound > 0 ? at('link') : claims > 0 ? at('claims') : ment > 0 ? at('mentions') : 0;
    stage = GROUNDING_STAGES[si];
  }
  // Within-stage progress so the bar CLIMBS during a long stage (not frozen at the stage boundary). The claims
  // stage dominates wall-time, so measure it directly: distinct paragraphs with claims / disambiguated paragraphs.
  // Other stages get a 0.5 mid-estimate (they're short). percent = (stageIndex + withinFrac) / totalStages.
  const stageName = stage || GROUNDING_STAGES[si] || 'grounding';
  let withinFrac = 0.5;
  // PREFERRED: the executor reports REAL per-item progress (paras/clusters/uncertains settled ÷ job size) into
  // run_json.withinFrac — every long stage flows through pool()'s onProgress. Use it directly (no DB counts) so the
  // bar climbs continuously through EVERY stage; a flat bar then means work actually stopped, not "unobserved".
  if (run && typeof run.withinFrac === 'number') {
    withinFrac = Math.max(0, Math.min(0.999, run.withinFrac));
  } else if (stageName === 'disambiguate') {
    // Disambiguate is a full model pass over every prose paragraph — measure it directly (context-filled / total prose)
    // so the bar climbs through it instead of sitting flat.
    const totalPar = (await queryAll(`SELECT COUNT(*) n FROM content WHERE doc_id=? AND blocktype IN ('paragraph','quote') AND deleted_at IS NULL`, [docId]))[0]?.n || 0;
    const disPar = (await queryAll(`SELECT COUNT(*) n FROM content WHERE doc_id=? AND context IS NOT NULL`, [docId]))[0]?.n || 0;
    withinFrac = totalPar ? Math.min(0.99, disPar / totalPar) : 0.5;
  } else if (stageName === 'claims') {
    const totalPar = (await queryAll(`SELECT COUNT(*) n FROM content WHERE doc_id=? AND context IS NOT NULL`, [docId]))[0]?.n || 0;
    const claimedPar = (await queryAll(`SELECT COUNT(DISTINCT para_id) n FROM entity_claims WHERE doc_id=?`, [docId]))[0]?.n || 0;
    withinFrac = totalPar ? Math.min(0.99, claimedPar / totalPar) : 0.5;
  } else if (stageName === 'hype') {
    // HyPE is the other long stage on big books — measure it directly (paragraphs with questions / disambiguated).
    const totalPar = (await queryAll(`SELECT COUNT(*) n FROM content WHERE doc_id=? AND context IS NOT NULL`, [docId]))[0]?.n || 0;
    const hypePar = (await queryAll(`SELECT COUNT(*) n FROM content WHERE doc_id=? AND hyp_questions IS NOT NULL`, [docId]))[0]?.n || 0;
    withinFrac = totalPar ? Math.min(0.99, hypePar / totalPar) : 0.5;
  }
  // Bar weight per stage = its REAL job size (item count), measured PER BOOK. Fixed weights can't be right for
  // both a narrative (claims/paragraphs dominate) and a biographical volume (reconcile — thousands of clusters —
  // is >half the work). Each item ≈ one model call, so item-count is a good wall-time proxy: the stage that
  // actually takes the time gets the bar-share, so a long reconcile CLIMBS instead of sitting flat at ~68%.
  const sizes = await stageSizes(docId);
  const total = Object.values(sizes).reduce((a, b) => a + b, 0) || 1;
  let done = 0;
  for (let i = 0; i < GROUNDING_STAGES.length; i++) {
    const frac = i < si ? 1 : (i === si ? withinFrac : 0);   // prior stages full, current by within-frac, rest 0
    done += (sizes[GROUNDING_STAGES[i]] / total) * frac;
  }
  // HIGH-RESOLUTION float (2dp) — never the old integer that froze each whole-percent for ~a minute of real work.
  let percent = Math.max(3, Math.min(99, Math.round(done * 10000) / 100));
  // MONOTONIC per run (keyed by startedAt): clamp so the emitted percent can never regress at the source — kills
  // any backward jump from a re-weight / recompute / transient read. A genuinely new run (different startedAt) resets.
  const floor = _pctFloor.get(docId);
  if (floor && floor.startedAt === startedAt) percent = Math.max(percent, floor.pct);
  _pctFloor.set(docId, { startedAt, pct: percent });
  // Current-stage DETAIL (absolute done/total, now that stages report ABSOLUTE progress) — the "window into what's
  // happening" the bar surfaces: e.g. "Reconciling identities · 1,664 / 6,533".
  const stageDone = run?.itemsDone ?? null, stageTotal = run?.itemsTotal ?? null;
  const stageFrac = stageTotal ? Math.min(1, (stageDone || 0) / stageTotal) : withinFrac;
  // Always resolve the real title — the active book may not be in a phase (e.g. a stray-collection doc), so fall
  // back to the docs table rather than showing "doc <id>".
  let m = meta[docId];
  if (!m?.title) m = (await queryAll(`SELECT title, paragraph_count FROM docs WHERE id=?`, [docId]))[0] || m;
  const active = { docId, stage: stageName, stageIndex: si, totalStages: ts, percent, since: startedAt,
    stageDone, stageTotal, stageFrac: Math.round(stageFrac * 1000) / 1000,
    adjudicatorVersion: ADJUDICATOR_VERSION,   // the engine version this run is grounding with (shown in the progress box)
    title: m?.title || `doc ${docId}`, size: m?.paragraph_count || 0, claimsExtracted: claims };
  return remember(active);
}

/**
 * The live block for EVERY grounding book (freshest first). Books run in parallel by design, so this is the
 * list the UI tabs across; `active` (singular, = the first) stays for callers that just want "the current book".
 */
async function computeActiveBooks(staticDocs, meta) {
  const runs = await pipelineState.activeRuns();
  if (!runs.length) {                                   // nothing reported → let the claim-write fallback try
    const one = await computeActiveBook(null, staticDocs, meta);
    return one ? [one] : [];
  }
  const blocks = await Promise.all(runs.map((r) => computeActiveBook(r, staticDocs, meta)));
  return blocks.filter(Boolean);
}

// Integration progress for the biography "progress" popup — the phased roadmap (integration-phases.js): every
// book in sequence with its SIZE (paragraph_count), LIVE grounded-person count, and the currently-active book.
// The phase structure is cached briefly; the `active` block is recomputed on EVERY call so polling stays live.
let _progCache = null, _progAt = 0;
export async function getIntegrationProgress() {
  // genreOf is DISPLAY-ONLY now (the biographies/histories genre labels) — it no longer decides membership.
  const genreOf = Object.fromEntries(readHistoryCatalog().map(b => [b.id, b.genre]));
  // Membership is EXPLICIT: a doc is in the plan IFF its id is listed in integration-phases.js. No author-routing,
  // no collection sweep, no genre auto-classification — nothing rides in on a rule. (Pilgrim-group docs, primary.groups,
  // render as a separate tree below and are intentionally NOT part of phaseByDoc / the graded metrics.)
  const phaseByDoc = {};
  for (const p of INTEGRATION_PHASES) for (const id of (p.docs || [])) phaseByDoc[id] = p.key;
  const allDocs = [...new Set(Object.keys(phaseByDoc).map(Number))];

  // Size + title/author for EVERY book (chunked to stay under the SQLite param limit).
  const meta = {};
  for (let i = 0; i < allDocs.length; i += 800) {
    const chunk = allDocs.slice(i, i + 800), cp = chunk.map(() => '?').join(',');
    (await queryAll(`SELECT id, title, author, paragraph_count FROM docs WHERE id IN (${cp}) AND deleted_at IS NULL AND duplicate_of IS NULL`, chunk))
      .forEach(d => { meta[d.id] = d; });
  }
  const curatedKeys = new Set(INTEGRATION_PHASES.filter(p => !p.dynamic).map(p => p.key));
  const gradedDocs = allDocs.filter(id => curatedKeys.has(phaseByDoc[id])); // curated docs that may be grounded
  // `actives` = every book grounding right now (parallel runs are normal); `active` = the first, kept so existing
  // callers/UI keep working. Always fresh (cheap) → live polling.
  const actives = await computeActiveBooks(gradedDocs, meta);
  const active = actives[0] || null;
  const offPeak = await computeOffPeakHint();   // {waiting, resumesAt} — books held for cheap DeepSeek hours (fresh, cheap)

  if (_progCache && Date.now() - _progAt < 60000) return { ..._progCache, active, actives, offPeak };

  // Grounded metrics run over the curated (non-dynamic) docs in phase order — biographies/histories aren't grounded yet.
  const ph = gradedDocs.map(() => '?').join(',');
  const counts = {}, unresolved = {};
  (await queryAll(`SELECT doc_id, COUNT(*) n FROM (
      SELECT doc_id, entity_id FROM entity_mentions_v2 WHERE doc_id IN (${ph}) AND entity_id IS NOT NULL
      UNION SELECT doc_id, entity_id FROM entity_claims WHERE doc_id IN (${ph}) AND entity_id IS NOT NULL
    ) GROUP BY doc_id`, [...gradedDocs, ...gradedDocs])).forEach(r => { counts[r.doc_id] = r.n; });
  (await queryAll(`SELECT CAST(json_extract(payload,'$.docId') AS INT) d, COUNT(*) n FROM entity_decisions
      WHERE kind='uncertain' AND status='proposed' GROUP BY d`)).forEach(r => { if (r.d) unresolved[r.d] = r.n; });
  // HONEST "done": a book is done only when reconcile has actually adjudicated its cast — decisions exist AND cover
  // most of its name-clusters. Just having ≥1 legacy-bound person is NOT done (the Covenant books had 0 decisions
  // yet showed ✓). decsByDoc counts reconcile decisions; clustersByDoc counts distinct resolvable names.
  const decsByDoc = {}, clustersByDoc = {}, adjVerByDoc = {};
  (await queryAll(`SELECT CAST(json_extract(payload,'$.docId') AS INT) d, COUNT(*) n FROM entity_decisions
      WHERE target_kind='mention-cluster' GROUP BY d`)).forEach(r => { if (r.d) decsByDoc[r.d] = r.n; });
  (await queryAll(`SELECT doc_id d, COUNT(DISTINCT resolved_as) n FROM entity_mentions_v2
      WHERE doc_id IN (${ph}) AND resolved_as IS NOT NULL AND resolved_as NOT LIKE '%?%' GROUP BY doc_id`, gradedDocs))
    .forEach(r => { clustersByDoc[r.d] = r.n; });
  // Adjudicator version = the HIGHEST engine version that has produced decisions for this book — i.e. the version
  // it was LAST processed at. A pre-EEWA decision has NULL method_version → v1 (the original thin reconcile); an
  // EEWA re-sweep writes v2 decisions → MAX = 2. MAX (not MIN) is the point of the badge: "has this book been
  // upgraded to the current engine?" A few stragglers (parse-failures that kept a v1 decision) must NOT drag a
  // swept book back to v1. (No decisions → absent → 0 → hidden.)
  (await queryAll(`SELECT CAST(json_extract(payload,'$.docId') AS INT) d,
      MAX(COALESCE(CAST(method_version AS INT), 1)) v FROM entity_decisions
      WHERE target_kind='mention-cluster' GROUP BY d`)).forEach(r => { if (r.d) adjVerByDoc[r.d] = r.v; });
  // SPEND per book, from the central ai_usage log — what this book actually cost and on whose meter. Only
  // grounding calls (service_type 'grounding:<stage>') count, so chat/search spend never inflates a book.
  // Rolled up per provider because provider IS the story: deepseek is ~free, anthropic is the Persian budget.
  // CAST: document_id is a TEXT column, so numeric ids are stored as text — historically as '15254.0' (a bound
  // JS number under TEXT affinity). Grouping on the raw column would key this map by a string that never matches
  // an integer book id → every book reads $0. Cast on read so both new ('15254') and legacy ('15254.0') rows roll up.
  const costByDoc = {};
  // 6dp, not 2: an individual call costs ~1e-5, so rounding to cents floors a real cost to $0 — under-reporting
  // is the same failure as not reporting. Sum first, round once.
  // Match on the CALLER as well as the stage tag: a grounding call is a corpus-rag call whatever its stage
  // label, so a row logged before the stage tag existed (or from a stage-less path) still counts toward its book.
  (await queryAll(`SELECT CAST(document_id AS INT) d, provider p, ROUND(SUM(estimated_cost_usd), 6) usd, COUNT(*) calls
      FROM ai_usage WHERE (service_type LIKE 'grounding:%' OR caller = 'corpus-rag') AND document_id IS NOT NULL
      GROUP BY d, p`))
    .forEach(({ d, p, usd, calls }) => {
      const c = (costByDoc[d] ||= { usd: 0, calls: 0, byProvider: {} });
      c.usd = Math.round((c.usd + usd) * 1e6) / 1e6; c.calls += calls; c.byProvider[p] = usd;
    });
  // Done ⇔ the book reached FULL grounding, tested by the SAME reachedBound() the queue uses to decide a run
  // finished — one definition of "done", so the roadmap ✓ can never disagree with the pipeline. Reconcile alone
  // is NOT enough: a read-half-only book (disambiguate→reconcile done, but the graph tail + HyPE never ran → 0
  // entity bindings, 0 hyp_questions) has decisions covering its clusters (clusters exist only for processed
  // paragraphs) yet is not grounded. That was the 8322/9095 leak — both showed ✓ on reconcile while fully
  // unprojected + un-HyPE'd. reachedBound(verify) requires disamb≥98% + mentions + claims + reconcile + HyPE.
  const doneByDoc = {};
  await Promise.all(gradedDocs.map(async (id) => { try { doneByDoc[id] = await reachedBound(id, {}); } catch { doneByDoc[id] = false; } }));
  const isGrounded = (id) => doneByDoc[id] === true;
  // Order IS the hard-coded list order (integration-phases.js was snapshotted in the intended grounding sequence).
  // No dynamic re-sort — the list is the order, so the roadmap and the follower that walks it stay stable and match
  // the file exactly. A listed id that's since been soft-deleted/dup'd has no meta → filtered out here.
  const phaseBookIds = {};
  for (const p of INTEGRATION_PHASES) phaseBookIds[p.key] = (p.docs || []).filter((id) => meta[id]);
  // New-in-sequence: the first book (in ABSORPTION order) to ground each entity → each book's NET contribution.
  const orderedGraded = INTEGRATION_PHASES.filter(p => !p.dynamic).flatMap(p => phaseBookIds[p.key]);
  const order = {}; orderedGraded.forEach((d, i) => { order[d] = i; });
  const firstSeen = {}, newBy = {};
  (await queryAll(`SELECT doc_id d, entity_id e FROM entity_mentions_v2 WHERE doc_id IN (${ph}) AND entity_id IS NOT NULL
      UNION SELECT doc_id, entity_id FROM entity_claims WHERE doc_id IN (${ph}) AND entity_id IS NOT NULL`, [...gradedDocs, ...gradedDocs]))
    .forEach(({ d, e }) => { const o = order[d]; if (o !== undefined && (firstSeen[e] === undefined || o < firstSeen[e])) firstSeen[e] = o; });
  for (const e in firstSeen) { const d = orderedGraded[firstSeen[e]]; newBy[d] = (newBy[d] || 0) + 1; }

  const book = (id, extra = {}) => ({ id, title: meta[id]?.title || `doc ${id}`, author: meta[id]?.author || null,
    size: meta[id]?.paragraph_count || 0, persons: counts[id] || 0, newInSequence: newBy[id] || 0,
    unresolved: unresolved[id] || 0, done: isGrounded(id),
    adjVersion: adjVerByDoc[id] ?? 0, adjCurrent: ADJUDICATOR_VERSION,
    cost: costByDoc[id] || { usd: 0, calls: 0, byProvider: {} }, ...extra });
  const phases = INTEGRATION_PHASES.map(p => {
    const books = phaseBookIds[p.key].map(id => book(id, p.dynamic ? { genre: genreOf[id] } : {}));
    return { key: p.key, label: p.label, blurb: p.blurb, upcoming: !!p.upcoming, books,
      done: books.filter(b => b.done).length, total: books.length,
      persons: books.reduce((s, b) => s + b.persons, 0), paras: books.reduce((s, b) => s + b.size, 0),
      usd: Math.round(books.reduce((s, b) => s + b.cost.usd, 0) * 100) / 100 };
  });

  // Pilgrim Notes — the Primary phase's per-period sub-groups, from the EXPLICIT hard-coded group lists
  // (integration-phases.js `primary.groups`), NOT a collection sweep. Resolve title/size + a has-claims "grounded"
  // flag per id; a soft-deleted/duplicate id drops out (meta filter), so the tree only shows live, listed docs.
  const primarySpec = INTEGRATION_PHASES.find((p) => p.key === 'primary');
  if (primarySpec?.groups?.length) {
    const groupIds = [...new Set(primarySpec.groups.flatMap((g) => g.docs || []))];
    const gmeta = {}; const grounded = new Set();
    for (let i = 0; i < groupIds.length; i += 800) {
      const c = groupIds.slice(i, i + 800), cp = c.map(() => '?').join(',');
      (await queryAll(`SELECT id, title, paragraph_count FROM docs WHERE id IN (${cp}) AND deleted_at IS NULL AND duplicate_of IS NULL`, c)).forEach((d) => { gmeta[d.id] = d; });
      (await queryAll(`SELECT DISTINCT doc_id d FROM entity_claims WHERE doc_id IN (${cp})`, c)).forEach((r) => grounded.add(r.d));
    }
    const groups = primarySpec.groups.map((g) => {
      const books = (g.docs || []).filter((id) => gmeta[id]).map((id) => ({ id, title: gmeta[id].title, size: gmeta[id].paragraph_count || 0, done: grounded.has(id) }));
      return { label: g.label, books, total: books.length, done: books.filter((b) => b.done).length, paras: books.reduce((s, b) => s + b.size, 0) };
    });
    const primary = phases.find((p) => p.key === 'primary');
    if (primary) {
      primary.groups = groups;
      primary.total += groups.reduce((s, g) => s + g.total, 0);
      primary.done += groups.reduce((s, g) => s + g.done, 0);
      primary.paras += groups.reduce((s, g) => s + g.paras, 0);
    }
  }
  const doneBooks = phases.reduce((s, p) => s + (p.upcoming ? 0 : p.done), 0);
  const totalBooks = phases.reduce((s, p) => s + p.total, 0);
  // Cumulative UNIQUE people grounded across the curated books (deduped — a figure in N books counts once).
  const cumulativeUnique = (await queryAll(`SELECT COUNT(*) n FROM (
      SELECT entity_id e FROM entity_mentions_v2 WHERE doc_id IN (${ph}) AND entity_id IS NOT NULL
      UNION SELECT entity_id FROM entity_claims WHERE doc_id IN (${ph}) AND entity_id IS NOT NULL)`, [...gradedDocs, ...gradedDocs]))[0]?.n || 0;
  const totalParas = phases.reduce((s, p) => s + p.paras, 0);
  _progCache = { phases, doneBooks, totalBooks, cumulativeUnique, totalParas, goal: 'all history absorbed' };
  _progAt = Date.now();
  return { ..._progCache, active, actives, offPeak };
}

// Off-peak hold hint for the progress UI: is DeepSeek work QUEUED but held for the cheap window? If so, when does
// it resume? Non-sensitive (no dollar figures) so it rides the public /people/progress endpoint. Fresh each poll.
async function computeOffPeakHint() {
  try {
    const rows = await queryAll(`SELECT peak_windows FROM grounding_budget WHERE offpeak_only=1`);
    if (!rows.length) return { waiting: false, resumesAt: null };
    const now = new Date();
    let resumesAt = null;
    for (const r of rows) {
      let w = DEFAULT_PEAK_WINDOWS; try { if (r.peak_windows) w = JSON.parse(r.peak_windows); } catch { /* default */ }
      if (!nowInPeak(w, now)) continue;
      const e = peakEndsAt(w, now); if (!e) continue;
      const ts = Math.floor(e.getTime() / 1000);
      resumesAt = resumesAt == null ? ts : Math.min(resumesAt, ts);
    }
    if (resumesAt == null) return { waiting: false, resumesAt: null };
    const q = await queryOne(`SELECT COUNT(*) n FROM grounding_queue WHERE status='queued'`);
    return { waiting: (q?.n || 0) > 0, resumesAt: (q?.n || 0) > 0 ? resumesAt : null };
  } catch { return { waiting: false, resumesAt: null }; }  // tables may not exist (tests/fresh db)
}

// The full person dataset for the browser + API list endpoint. Cached briefly (data changes rarely; the book-
// source computation is ~2s) so per-request API calls stay fast.
let _listCache = null, _listAt = 0;
export async function listBioPersons() {
  if (_listCache && Date.now() - _listAt < 300000) return _listCache;
  const man = readBioManifest();
  const bookOf = await computeBookSources();
  const rows = await queryAll(`SELECT ge.id, ge.canonical_name AS name, ge.importance,
      er.side, er.summary, er.aliases, er.kinship, er.research_notes
    FROM graph_entities ge LEFT JOIN entity_research er ON er.canonical_name = ge.canonical_name
    WHERE ge.entity_type = 'person' AND ge.religion = ''
      AND (ge.last_assessed_version IS NULL OR ge.last_assessed_version NOT LIKE 'merged-into-%')
    ORDER BY (ge.importance IS NULL), ge.importance DESC, ge.canonical_name`);
  const persons = rows.map(r => {
    let aliases = [], kinship = [], death = null;
    try { aliases = JSON.parse(r.aliases || '[]'); } catch {}
    try { kinship = JSON.parse(r.kinship || '[]'); } catch {}
    try { death = JSON.parse(r.research_notes || '{}').death || null; } catch {}
    const m = man[r.id]; const hasPortrait = !!(m && m.cdn);
    return { id: r.id, name: r.name, importance: r.importance || 0, side: r.side || null,
      summary: r.summary || null, aliases, kinship, death, hasPortrait, sources: [...(bookOf[r.id] || [])],
      portrait: m?.cdn || null,
      wiki: m?.title ? `https://en.wikipedia.org/wiki/${encodeURIComponent(String(m.title).replace(/ /g, '_'))}` : null };
  });
  // QA scope: the browser shows the genuine cast of the core books — only persons grounded by a GPB/Dawn-Breakers
  // mention. This excludes ungrounded artifacts (duplicate "Bahá'u'lláh", generic "Bahá'í pilgrim", out-of-corpus
  // names) without deleting them. As the Pillars books are ingested, their mentions will admit more of the cast.
  const grounded = persons.filter(p => p.sources.length);
  const sides = [...new Set(grounded.map(p => p.side).filter(Boolean))].sort();
  const books = SOURCE_BOOKS.map(b => ({ key: b.key, label: b.label, count: grounded.filter(p => p.sources.includes(b.key)).length }));
  _listCache = { count: grounded.length, withPortraits: grounded.filter(p => p.hasPortrait).length, sides, books, persons: grounded };
  _listAt = Date.now();
  return _listCache;
}

// Full dossier for one person: DB record + gathered portrait/bio.json + cross-corpus reach + GPB citations.
export async function getBioPerson(rawId) {
  const id = String(rawId).replace(/[^0-9]/g, '');
  const row = await queryOne(`SELECT ge.id, ge.canonical_name AS name, ge.importance, ge.last_assessed_version AS lav, er.side, er.summary,
      er.aliases, er.kinship, er.relations, er.research_notes, er.dates
    FROM graph_entities ge LEFT JOIN entity_research er ON er.canonical_name = ge.canonical_name WHERE ge.id = ?`, [id]);
  if (!row || /^merged-into-/.test(row.lav || '')) return null;   // merged duplicate → gone (references live on the survivor)
  const arr = s => { try { return JSON.parse(s || '[]'); } catch { return []; } };
  const obj = s => { try { return JSON.parse(s || '{}'); } catch { return {}; } };
  let wiki = null, portrait = null, portraitFull = null, bahai = null;
  portrait = readBioManifest()[id]?.cdn || null;
  try {
    const d = fs.readdirSync(BIO_ROOT).find(x => x.startsWith(id + '-'));
    if (d) { const bj = JSON.parse(fs.readFileSync(path.join(BIO_ROOT, d, 'bio.json'), 'utf8'));
      wiki = bj.wikipedia || null; bahai = bj.bahai_media || null;
      portraitFull = bj.portrait_fullres || bj.wikipedia?.image_url || bahai?.full || null; }
  } catch { /* no bio.json */ }
  let mentionCount = 0, books = [], gpbRefs = [];
  try {
    // Cross-corpus reach from the disambiguated v2 substrate (doc_id + para_id carried directly).
    const ms = await queryAll('SELECT doc_id, para_id FROM entity_mentions_v2 WHERE entity_id = ?', [id]);
    mentionCount = ms.length;
    const dids = [...new Set(ms.map(m => m.doc_id))];
    if (dids.length) {
      books = (await queryAll(`SELECT DISTINCT title FROM docs WHERE id IN (${dids.map(() => '?').join(',')}) AND title IS NOT NULL`, dids)).map(b => b.title);
      const gpids = [...new Set(ms.filter(m => m.doc_id === 21310 || m.doc_id === 57347).map(m => m.para_id))].slice(0, 24);
      if (gpids.length) {
        const ph = gpids.map(() => '?').join(',');  // para_id stores either external_para_id or 'p'||content.id — match both
        const gp = await queryAll(`SELECT c.external_para_id AS pid, c.text, c.heading, d.source_url AS url FROM content c JOIN docs d ON d.id = c.doc_id
          WHERE c.doc_id IN (21310, 57347) AND (c.external_para_id IN (${ph}) OR 'p'||c.id IN (${ph})) ORDER BY c.id LIMIT 24`, [...gpids, ...gpids]);
        gpbRefs = gp.map(r => ({ paraId: r.pid, url: r.url ? `${r.url}?paraId=${r.pid}` : null, heading: r.heading || null, snippet: String(r.text || '').replace(/\s+/g, ' ').slice(0, 200) }));
      }
    }
  } catch { /* mentions optional */ }
  const notes = obj(row.research_notes);
  // NEW substrate first: cited claims (proof-gated, temporal, source-linked) from entity_claims — the reconciled
  // evidence base. Fall back to legacy facts2/episodes only for entities the pipeline hasn't covered. Same UI shape.
  const claimRows = await queryAll(`SELECT relation, statement, proof_verbatim AS proof, doc_id, para_id, time_value AS tv, time_basis AS tb
     FROM entity_claims WHERE entity_id = ? AND (status IS NULL OR status = 'supported') ORDER BY (tv IS NULL), tv`, [id]);
  let characterizations;
  if (claimRows.length) {
    // Resolve each cited claim's source document (title + public url) from the docs table — NOT a hardcoded book list.
    // Every claim carries doc_id + para_id, so every fact shows its book + paragraph citation, clickable when online.
    const dids = [...new Set(claimRows.map(c => c.doc_id).filter(Boolean))];
    const dmap = new Map();
    if (dids.length) (await queryAll(`SELECT id, title, source_url FROM docs WHERE id IN (${dids.map(() => '?').join(',')})`, dids)).forEach(r => dmap.set(r.id, { title: r.title || null, url: r.source_url || null }));
    characterizations = claimRows.map(c => { const d = dmap.get(c.doc_id) || {}; return { quote: c.statement, proof: c.proof || null, relation: c.relation || null,
      when: c.tv ? `${c.tv}${c.tb ? ' [' + c.tb + ']' : ''}` : null, source: d.title || null, paraId: c.para_id, _doc: c.doc_id,
      url: d.url && c.para_id ? `${d.url}?paraId=${c.para_id}` : null }; });
  } else {  // fallback: legacy fact catalog for entities not yet re-extracted
    characterizations = Array.isArray(notes.facts2) && notes.facts2.length
      ? notes.facts2.map(f => ({ quote: f.statement, proof: f.quote || null, relation: f.relation || null, when: f.when || null, source: f.source, paraId: f.paraId, url: f.url || null }))
      : (notes.characterizations || []);
    if (Array.isArray(notes.episodes)) for (const e of notes.episodes) characterizations.push({ quote: e.statement, proof: e.quote || null, relation: 'episode', episode: e.name, when: e.when || null, source: e.source, paraId: e.paraId, url: e.url || null });
  }
  // compact citation label per fact: short source + paragraph number (e.g. "GPB ¶72", "DB ¶467"); works for any book.
  try {
    const pids = [...new Set(characterizations.map(c => c.paraId).filter(Boolean))];
    if (pids.length) {
      const ixRows = await queryAll(`SELECT doc_id, external_para_id pid, paragraph_index pix FROM content WHERE external_para_id IN (${pids.map(() => '?').join(',')})`, pids);
      const ix = {}; for (const r of ixRows) ix[`${r.doc_id}:${r.pid}`] = r.pix;
      const abbrOf = (s) => s === 'The Dawn-Breakers' ? 'DB' : s === 'God Passes By' ? 'GPB' : (String(s || '').split(/\s+/).filter(Boolean).map(w => w[0]).join('').toUpperCase().slice(0, 4) || 'SRC');
      for (const c of characterizations) {
        const n = c._doc != null ? ix[`${c._doc}:${c.paraId}`] : null;
        c.cite = n != null ? `${abbrOf(c.source)} ¶${n}` : abbrOf(c.source);
        delete c._doc;
      }
    }
  } catch { /* citation labels optional */ }
  return { id: row.id, name: row.name, importance: row.importance || 0, side: row.side || null,
    summary: row.summary || null, aliases: arr(row.aliases), kinship: arr(row.kinship), relations: arr(row.relations),
    dates: arr(row.dates), death: notes.death || null, characterizations,
    facts: notes.facts || [], firewall: notes.firewall || [], contested: notes.contested || [],
    possible_ids: notes.possible_ids || [], wiki, portrait, portraitFull, bahai, mentionCount, books, gpbRefs };
}

// Intelligent meaning-search over the cast (descriptive/reasoning queries the token filter can't do, e.g.
// "letters of the living who died at Shaykh Ṭabarsí"). Resolves known groups deterministically from
// graph_relations; otherwise asks DeepSeek to judge from summaries. Returns { ids, q, group?, reasoning }.
export async function bioSearch(rawQ) {
  const q = String(rawQ || '').trim().slice(0, 200);
  if (!q) return { ids: [], q };
  const norm = (s) => String(s || '').normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^a-z ]/gi, ' ').toLowerCase();
  const STOP = new Set(['the', 'of', 'and', 'who', 'a', 'an', 'in', 'at', 'to', 'is', 'are', 'were', 'all', 'show', 'me', 'list', 'group']);
  const qtok = new Set(norm(q).split(/\s+/).filter((t) => t.length > 2 && !STOP.has(t)));

  // deterministic group resolution: if the query names a modeled group, return its members from graph_relations
  let memberIds = [], bareGroup = false, best = null;
  const groups = await queryAll(`SELECT ge.id, ge.canonical_name AS name, er.aliases, er.summary FROM graph_entities ge
    LEFT JOIN entity_research er ON er.canonical_name = ge.canonical_name WHERE ge.entity_type='group'`);
  for (const g of groups) {
    const names = [g.name, ...(() => { try { return JSON.parse(g.aliases || '[]'); } catch { return []; } })()];
    for (const nm of names) {
      const gtok = norm(nm).split(/\s+/).filter((t) => t.length > 2 && !STOP.has(t));
      const overlap = gtok.filter((t) => qtok.has(t)).length;
      if (overlap >= 2 && (!best || overlap > best.ov)) best = { id: g.id, ov: overlap, name: g.name, summary: g.summary };
    }
  }
  if (best) {
    const mem = await queryAll(`SELECT gr.source_entity_id AS id FROM graph_relations gr JOIN graph_entities ge ON ge.id = gr.source_entity_id
      WHERE gr.target_entity_id = ? AND ge.entity_type='person' ORDER BY (ge.importance IS NULL), ge.importance DESC`, [best.id]);
    memberIds = [...new Set(mem.map((r) => r.id))];
    bareGroup = best.ov >= qtok.size;
  }
  if (bareGroup && memberIds.length) return { ids: memberIds, q, group: best.id, reasoning: { summary: best.summary || `${best.name} — ${memberIds.length} members.`, evidence: {} } };

  // ── Candidate catalog = each person's PROOF-GATED CLAIMS (entity_claims): every fact carries a verbatim proof span
  //    AND a source-paragraph citation, and connections are TYPED (relation + target-entity id). This replaces the
  //    legacy facts2/episodes catalog, whose uncited research-minted facts produced fabrications — e.g. a "genuine
  //    dervish who embraced the Faith under Bahá'u'lláh" fact miscited to GPB ¶369 (actually the Azal-poisoning
  //    paragraph) wrongly filed on the 1850 martyr Mírzá Qurbán-‘Alí. A claim with no proof span is not evidence.
  const fold = (s) => String(s || '').normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/['‘’`ʻ"“”]/g, '').replace(/\s+/g, ' ').toLowerCase().trim();
  const HON = new Set('mirza haji hajji mulla siyyid sayyid aqa shaykh sheikh ustad karbilai karbala mashhadi hajj the of son daughter dervish native known as'.split(' '));
  const tokize = (s) => [...new Set(fold(s).split(/[^a-z0-9]+/).filter((t) => t.length > 2 && !STOP.has(t) && !HON.has(t)))];

  const claimRows = await queryAll(`SELECT ec.entity_id eid, ge.canonical_name name, ge.importance imp, ec.relation, ec.target_entity_id tid,
      ec.statement, ec.proof_verbatim proof, ec.doc_id doc, ec.para_id pid, ec.time_value tv, ec.time_basis tb
    FROM entity_claims ec JOIN graph_entities ge ON ge.id = ec.entity_id
    WHERE ge.entity_type = 'person' AND ge.religion = '' AND (ec.status IS NULL OR ec.status = 'supported')
      AND ec.proof_verbatim IS NOT NULL AND TRIM(ec.proof_verbatim) <> ''
      AND (ge.last_assessed_version IS NULL OR ge.last_assessed_version NOT LIKE 'merged-into-%')`);
  // Resolve the SOURCE DOCUMENT for every cited claim from the docs table (NOT a hardcoded book list). Every claim
  // carries doc_id + para_id by construction, so every fact shows its book + paragraph citation; the clickable
  // oceanlibrary link is added when the book has a source_url. A fact without a citation cannot exist here.
  const docIds = [...new Set(claimRows.map((c) => c.doc).filter(Boolean))];
  const docMap = new Map();
  for (let i = 0; i < docIds.length; i += 800) { const ch = docIds.slice(i, i + 800); (await queryAll(`SELECT id, title, source_url FROM docs WHERE id IN (${ch.map(() => '?').join(',')})`, ch)).forEach((r) => docMap.set(r.id, { title: r.title || null, url: r.source_url || null })); }
  // resolve target-entity display names so typed connections read naturally
  const tids = [...new Set(claimRows.map((c) => c.tid).filter(Boolean))];
  const tname = new Map();
  for (let i = 0; i < tids.length; i += 800) { const ch = tids.slice(i, i + 800); (await queryAll(`SELECT id, canonical_name cn FROM graph_entities WHERE id IN (${ch.map(() => '?').join(',')})`, ch)).forEach((r) => tname.set(r.id, r.cn)); }
  const exById = {}; const nameById = {}; const impById = {};
  for (const c of claimRows) {
    nameById[c.eid] = c.name; impById[c.eid] = c.imp || 0;
    const target = c.tid ? (tname.get(c.tid) || null) : null;
    const d = docMap.get(c.doc) || {};
    const claim = { relation: c.relation || null, tid: c.tid || null, target,
      statement: c.statement, proof: c.proof, when: c.tv ? `${c.tv}${c.tb ? ' [' + c.tb + ']' : ''}` : null,
      source: d.title || null, paraId: c.pid || null, url: d.url && c.pid ? `${d.url}?paraId=${c.pid}` : null,
      hay: fold(`${c.statement} ${c.proof} ${target || ''}`) };
    (exById[c.eid] || (exById[c.eid] = [])).push(claim);
  }

  // ── Connection target: does the query name a person the subjects must be CONNECTED to? Resolve to an ENTITY. The
  //    group's own name tokens are excluded so the SUBJECT group ("Seven Martyrs") can't be mistaken for the OBJECT
  //    ("Bahá'u'lláh"). A connection then counts when a claim's TARGET is that entity OR the claim's verbatim proof
  //    NAMES it — object_id binding is incomplete, so the proof text carries the cited connection ("visited Bahá'u'lláh").
  const cl = (s) => String(s || '').replace(/\s+/g, ' ').trim();
  const connQ = /\b(met|meet|with|accompan|knew|know|present|encounter|together|companion|recogni|imprison|attain|visit|serv|correspond)\b/i.test(q);
  let connTarget = null;
  if (connQ) {
    const gtoks = new Set(best ? tokize(best.name) : []);
    const persons = await queryAll(`SELECT id, canonical_name cn FROM graph_entities WHERE entity_type = 'person'
      AND (last_assessed_version IS NULL OR last_assessed_version NOT LIKE 'merged-into-%')`);
    const qf = ' ' + fold(q) + ' ';
    for (const p of persons) {
      if (best && p.id === best.id) continue;
      const pt = tokize(p.cn).filter((t) => !gtoks.has(t)); if (!pt.length) continue;   // ignore tokens shared with the subject group
      if (pt.every((t) => qf.includes(t))) { const score = pt.join('').length; if (!connTarget || score > connTarget.score) connTarget = { id: p.id, name: p.cn, tok: pt, score }; }
    }
  }
  // a claim connects a subject to the target if it's typed to the target OR its proof/statement names the target
  const namesTarget = (c) => connTarget && (c.tid === connTarget.id || (connTarget.tok.length && connTarget.tok.every((t) => c.hay.includes(t))));

  // place/event tokens beyond the target name, the group name, and generic connection verbs — these reveal whether a
  // matched group is the query's SUBJECT ("Seven Martyrs who met X" → specificToks empty) or just an incidental
  // name-token overlap ("companions imprisoned with X in the Síyáh-Chál" matching a "…of Bahá'u'lláh" group).
  const GEN = new Set(['met', 'meet', 'with', 'accompanied', 'accompany', 'knew', 'know', 'present', 'encounter', 'together', 'companion', 'companions', 'recognized', 'recognize', 'imprisoned', 'attained', 'visited', 'served', 'who', 'whom', 'did']);
  const nameTokens = new Set([...(connTarget ? tokize(connTarget.name) : []), ...(best ? tokize(best.name) : [])]);
  const specificToks = [...tokize(q)].filter((t) => !nameTokens.has(t) && !GEN.has(t));

  // candidate scoping
  let candidateIds = null;
  const connected = connTarget ? Object.keys(exById).map(Number).filter((eid) => eid !== connTarget.id && exById[eid].some(namesTarget)) : null;
  if (best && connTarget) {
    candidateIds = memberIds.filter((id) => connected.includes(id));   // group ∩ cited connection
    if (!candidateIds.length) {
      // group IS the query's subject (no extra place/event token) and none of its members connect → honest "none".
      if (!specificToks.length) {
        const grpName = cl(best.name.replace(/\s*\(.*?\)\s*/g, ' ').replace(/^the\s+/i, ''));
        return { ids: [], q, group: best.id, reasoning: { summary: `No cited connection between the ${grpName} and ${connTarget.name} is recorded in God Passes By or The Dawn-Breakers.`, evidence: {} } };
      }
      candidateIds = connected;   // group was an incidental name-overlap → search the general cited-connected set
    }
  } else if (connTarget) {
    candidateIds = connected;
  }
  // NB: a group named WITHOUT a connection target (e.g. "Letters who died at Ṭabarsí") is left unscoped — the modeled
  // graph_relations membership is sparser than the claim data, so restricting to it under-returns; the term-matched
  // claim pool + the LLM's place/event judgement recovers the right people with better recall.

  // ── DETERMINISTIC broad-connection answer (a target, no extra place/event token): the cited-connected set IS the
  //    recall; the LLM only writes a clause per member from their connecting claim(s), and may drop one only if its
  //    proof does not actually bear the connection (SKIP). Place/event queries fall through to the precision path.
  if (connTarget && candidateIds && candidateIds.length && !specificToks.length) {
    const grp = best ? cl(best.name.replace(/\s*\(.*?\)\s*/g, ' ').replace(/\s+group$/i, '').replace(/^the\s+/i, '')) : '';
    const members = [];
    for (const id of candidateIds) {
      let conn = (exById[id] || []).filter(namesTarget);
      if (!conn.length) continue;
      // Every claim is cited, so choose for VIVIDNESS: drop claims whose proof merely "describes / refers to / extols"
      // the connection when a concrete sibling exists (one that shows the actual encounter — the embrace, the place),
      // prefer linkable, then the proof-richest. This is what lifts "met Bahá'u'lláh" → "…entered His presence in Ṭihrán".
      // vividness + support ranking. `vague` = a proof that only TALKS ABOUT the connection ("described/referred to/
      // mentioned/account of…") rather than showing it — PREFIX match so "described"/"mentioned" are caught. `pNames` =
      // the proof itself names the target (strong support), vs a claim that qualified only by its typed target_id with a
      // proof that names neither party (the inaccurate Ṭáhirih ¶754 case). Prefer proof-names-target, then non-vague,
      // then clickable, then proof-rich.
      const vague = (c) => /\b(describ|referr|mention|account|recount|allud|extol|prais|letter)/i.test(c.proof || '');
      const pNames = (c) => connTarget.tok.length > 0 && connTarget.tok.every((t) => fold(c.proof || '').includes(t));
      conn = [...conn].sort((a, b) => (pNames(b) ? 1 : 0) - (pNames(a) ? 1 : 0) || (vague(a) ? 1 : 0) - (vague(b) ? 1 : 0)
        || (b.url ? 1 : 0) - (a.url ? 1 : 0) || (b.proof || '').length - (a.proof || '').length).slice(0, 6);
      members.push({ id, name: nameById[id] || `#${id}`, conn });
    }
    if (members.length) {
      const CSYS = `For each person, choose the ONE fact that most CONCRETELY shows the connection the QUESTION asks about, and write a SPECIFIC clause (≤16 words, begin with a verb) that names the PLACE, TIME, or CIRCUMSTANCE of the connection. PREFER THE BOOK'S OWN WORDING taken verbatim from that fact's « proof » — lightly trimmed to a clean phrase — rather than paraphrasing (e.g. "was privileged to enter the presence of Bahá'u'lláh in Ṭihrán", "walked with Bahá'u'lláh in the streets of Badasht", "tenderly embraced Him and conducted Him to the place of honour"). NEVER write a bare "met X": do NOT choose a fact whose proof merely says someone "described", "referred to", or "mentioned" the person — prefer a fact whose proof shows the actual encounter (where/when/how it happened). Each fact is indexed "[i] statement « verbatim proof »". If NO fact actually shows the connection, use clause "SKIP". Return ONLY JSON: {"lead":"<one short sentence>","clauses":[{"id":<number>,"i":<chosen fact index>,"clause":"<specific book-worded verb phrase or SKIP>"}]}.`;
      const body = members.map((m) => `${m.id}|${m.name}:\n` + m.conn.map((c, i) => `  [${i}] ${cl(c.statement)} « ${cl(c.proof)} »`).join('\n')).join('\n');
      let lead = ''; const byId = {};
      try {
        const res = await chatCompletion([{ role: 'system', content: CSYS }, { role: 'user', content: `QUESTION: ${q}\n\n${body}` }],
          { provider: 'deepseek', model: 'deepseek-v4-flash', temperature: 0, maxTokens: 900, responseFormat: { type: 'json_object' } });
        const mm = (res.content || '').match(/\{[\s\S]*\}/); const p = mm ? JSON.parse(mm[0]) : {};
        lead = cl(p.lead || '');
        for (const c of (Array.isArray(p.clauses) ? p.clauses : [])) if (c && c.id != null) byId[Number(c.id)] = { i: Number.isInteger(+c.i) ? +c.i : 0, clause: cl(c.clause).slice(0, 140) };
      } catch { /* fall back to statements below */ }
      const stripName = (id, s) => { const nm = nameById[id] || ''; const re = new RegExp('^(' + nm.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + ')[\\s,;:—-]*', 'i'); return cl(s).replace(re, '').replace(/^[\s,;:—-]+/, ''); };
      const SKIP = /^\s*skip\s*$|\bno mention\b|\bno explicit\b|\bnot (?:mention|meet|met|present|clearly|established|recorded)\b|\bunclear\b|\bno (?:evidence|record|meeting)\b|\bdid not\b/i;
      const evidence = {}; const parts = []; const ids = [];
      for (const m of members) {
        const pick = byId[m.id] || {};
        const claim = m.conn[pick.i] || m.conn.find((c) => c.url) || m.conn[0];   // the claim the clause is drawn from → link to IT
        const clause = (pick.clause || stripName(m.id, claim.statement).split(/[;.]/)[0].slice(0, 120)).replace(/[\s.;,]+$/, '');
        if (SKIP.test(clause)) continue;   // proof doesn't bear the connection → drop, never assert
        // link ONLY to this claim's own citation (never borrow another's — that would miscite); show the book as text
        // when the source has no public URL, so the citation is ALWAYS visible.
        evidence[m.id] = { quote: cl(claim.statement), proof: cl(claim.proof) || null, source: claim.source, paraId: claim.paraId, url: claim.url || null, clause };
        parts.push(claim.url ? `${m.name} [${clause}](${claim.url})` : `${m.name} ${clause}${claim.source ? ' — ' + claim.source : ''}`);
        ids.push(m.id);
      }
      if (ids.length) {
        // the per-person clauses ARE the answer (each: name + book-worded evidence + link) — no enumerating lead that
        // just repeats the names. `lead`/`grp` are computed above but deliberately not prepended.
        const summary = `${parts.join('; ')}.`.replace(/\s+/g, ' ').trim();
        return { ids, q, ...(best ? { group: best.id } : {}), reasoning: { summary, evidence } };
      }
      if (best) return { ids: [], q, group: best.id, reasoning: { summary: `No cited connection between the ${grp} and ${connTarget.name} is borne out by the sources.`, evidence: {} } };
    }
  }
  // ── Precision path (place/event/meaning, incl. connection+place): judge the query over each candidate's cited claims.
  //    Pool = the cited-connected set (if a target was named) else entities whose claim proof/statement matches the query
  //    terms. Every candidate line carries the claim's VERBATIM PROOF so the model judges on evidence, not paraphrase.
  const qterms = tokize(q);
  const matchScore = (eid) => exById[eid].reduce((s, c) => s + qterms.filter((t) => c.hay.includes(t)).length, 0);
  let poolIds = candidateIds || Object.keys(exById).map(Number).filter((eid) => matchScore(eid) > 0);
  poolIds = poolIds.filter((id) => exById[id]).sort((a, b) => matchScore(b) - matchScore(a) || (impById[b] - impById[a])).slice(0, 60);
  const lines = poolIds.map((id) => {
    const fx = [...exById[id]].sort((a, b) => qterms.filter((t) => b.hay.includes(t)).length - qterms.filter((t) => a.hay.includes(t)).length);
    return `${id}|${nameById[id]}: ${fx.slice(0, 14).map((c) => `• ${cl(c.statement)} « ${cl(c.proof).slice(0, 160)} »${c.when ? ' [' + c.when + ']' : ''}`).join(' ')}`;
  });
  const catalog = lines.join('\n');

  const SYS = `You answer a question about people in early Bábí/Bahá'í history from a CATALOG of cited claims — one person per line: "id|name: • statement « verbatim proof » [period] • …" (from God Passes By and The Dawn-Breakers).
A person qualifies ONLY if one of their claims, AS SHOWN BY ITS VERBATIM PROOF, DIRECTLY satisfies the QUERY — the right act AND place AND period. Reject mere group membership. Reject "promised/prophesied/expected" when the query asks who actually DID or MET something. For a place/period query the proof must name that place/period.
For each qualifying person output {"id":<number>, "clause":"<a SHORT phrase answering the query for this person — PREFER the book's OWN wording taken verbatim from their « proof », lightly trimmed to a clean phrase, rather than paraphrasing; e.g. 'fell a martyr at the fort of Shaykh Ṭabarsí', 'was admitted into the presence of Bahá'u'lláh in Baghdád'>"}.
Also output "lead": one short sentence stating the overall answer.
Return ONLY JSON: {"lead":"...","matches":[{"id","clause"}]} — most relevant first, clear matches only.`;
  try {
    const res = await chatCompletion([{ role: 'system', content: SYS }, { role: 'user', content: `QUERY: ${q}\n\nCATALOG:\n${catalog}` }],
      { provider: 'deepseek', model: 'deepseek-v4-flash', temperature: 0, maxTokens: 2600, responseFormat: { type: 'json_object' } });
    // tolerant parse: DeepSeek occasionally emits malformed/truncated JSON — salvage the lead + every COMPLETE {...}.
    const looseParse = (txt) => {
      const whole = (txt || '').match(/\{[\s\S]*\}/);
      if (whole) { try { return JSON.parse(whole[0]); } catch { /* fall through to salvage */ } }
      const out = {}; const lead = (String(txt).match(/"lead"\s*:\s*"((?:[^"\\]|\\.)*)"/) || [])[1]; if (lead) out.lead = lead;
      const objs = []; const re = /\{[^{}]*\}/g; let o; while ((o = re.exec(String(txt)))) { try { objs.push(JSON.parse(o[0])); } catch { /* skip */ } }
      if (objs.length) out.matches = objs.filter((x) => x && x.id != null);
      return out;
    };
    const parsed = looseParse(res.content);
    const evidence = {}; const aiIds = []; const parts = [];
    for (const mm of (Array.isArray(parsed.matches) ? parsed.matches : [])) {
      const id = Number(mm.id); if (!id || aiIds.includes(id) || !exById[id]) continue;
      if (candidateIds && !candidateIds.includes(id)) continue;                       // never escape the candidate scope
      const fx = exById[id];
      // bind to the claim best matching the query (term overlap), preferring one that names the connection target
      const ranked = [...fx].sort((a, b) => qterms.filter((t) => b.hay.includes(t)).length - qterms.filter((t) => a.hay.includes(t)).length);
      const hit = (connTarget ? ranked.find(namesTarget) : null) || ranked[0];
      const clause = String(mm.clause || hit.statement).replace(/\s+/g, ' ').trim().slice(0, 160).replace(/[\s.;,]+$/, '');
      aiIds.push(id); evidence[id] = { quote: cl(hit.statement), proof: cl(hit.proof) || null, source: hit.source, paraId: hit.paraId, url: hit.url || null, clause };
      const nm = nameById[id] || `#${id}`;
      parts.push(hit.url ? `${nm} [${clause}](${hit.url})` : `${nm} ${clause}${hit.source ? ' — ' + hit.source : ''}`);
    }
    // no qualifying match: say so plainly rather than return a blank banner — especially for a connection query, where
    // the honest answer ("no cited connection with X") is itself the useful result (e.g. Seven Martyrs met Bahá'u'lláh).
    const explanation = parts.length
      ? `${parts.join('; ')}.`.trim()   // per-person clauses are the answer; no enumerating lead
      : (connTarget ? `No cited connection with ${connTarget.name} is recorded for anyone matching this query in God Passes By or The Dawn-Breakers.` : '');
    return { ids: aiIds, q, ...(best ? { group: best.id } : {}), reasoning: { summary: explanation, evidence } };
  } catch (e) { return { ids: memberIds, q, error: String(e).slice(0, 80) }; }
}
