// concepts/oceanoflights — use oceanoflights.org as a RESEARCH SOURCE to find the original-language text
// parallel to a translation we already hold, so we can enrich OUR document with it.
//
// Chad, 2026-08-26: "I did not say to replace our content with oceanoflights… I just said to use it as a
// research point to find the parallel content." Nothing here ingests, replaces, or re-points a document.
// The only thing written is `original_text` (+ lang, provenance) on paragraphs we already own.
//
// ── WHY THIS WORKS: THE SITE IS A PARALLEL CORPUS, AND ITS FILENAMES SAY SO ──────────────────────────────
// Each passage exists per language under one stem:
//     001-for-interpretation-of-the-holy-writings_en.docx
//     001-for-interpretation-of-the-holy-writings_ar.docx
// So the hard half of the problem — deciding which Arabic text corresponds to which English — is answered
// by the source itself, deterministically. What remains on our side is ENGLISH-to-ENGLISH matching against
// our own copy, which is the alignment already proven at 99% on the CTAI works.
//
// This matters because it reaches the books CTAI cannot: CTAI is a concordance of Shoghi Effendi's
// renderings, so the Kitáb-i-Aqdas, Some Answered Questions and the Tablets of the Divine Plan are absent
// from it — and those are precisely the works where the original carries the MOST weight, because their
// English is not his and fixes no sense (Chad, 2026-08-25).
//
// ⚠ THE SCRAPED PAGES IN OUR CORPUS ARE NAVIGATION CHROME, NOT TEXT. All 66,000 of them hold "Content"
// plus links to `/file/autogenerated/<stem>_<lang>.docx`. Measured 2026-08-26 — reading them as scripture
// yields a table of markdown links. The stems are the only thing worth taking from them; the text has to
// come from the linked file.
// Deps: jszip (docx is a zip), align.js (pure), global fetch.

import { alignSequences, detectSourceLang } from './align.js';

const BASE = 'https://oceanoflights.org/file/autogenerated';
const TIMEOUT_MS = 45000;

/** Strip the language suffix from a scraped path to get the stem shared across languages. Pure. */
export function stemOf(filePath) {
  const base = String(filePath || '').split('/').pop() || '';
  const m = base.match(/-(ar|en|fa|es|fr|de|pt|ru|zh|he|tr|ur|hi)-?\.md$/);
  return m ? base.slice(0, m.index) : null;
}

/** Paragraphs of one .docx, in order. Pure given the buffer. */
export async function docxParagraphs(buf) {
  const JSZip = (await import('jszip')).default;
  const zip = await JSZip.loadAsync(buf);
  const xml = await zip.file('word/document.xml')?.async('string');
  if (!xml) return [];
  const out = [];
  for (const m of xml.match(/<w:p[ >][\s\S]*?<\/w:p>/g) || []) {
    const text = (m.match(/<w:t[^>]*>([\s\S]*?)<\/w:t>/g) || [])
      .map((t) => t.replace(/<[^>]+>/g, ''))
      .join('')
      .replace(/&quot;/g, '"').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
      .replace(/\s+/g, ' ').trim();
    if (text) out.push(text);
  }
  return out;
}

/**
 * Fetch one language of one stem. Returns null when the site does not serve it — which is ordinary, not an
 * error: many passages exist in English only.
 */
export async function fetchStem(stem, lang, { log, cache = new Map() } = {}) {
  const key = `${stem}_${lang}`;
  if (cache.has(key)) return cache.get(key);
  try {
    const res = await fetch(`${BASE}/${key}.docx`, { signal: AbortSignal.timeout(TIMEOUT_MS) });
    if (!res.ok) { cache.set(key, null); return null; }
    const paras = await docxParagraphs(Buffer.from(await res.arrayBuffer()));
    cache.set(key, paras);
    return paras;
  } catch (err) {
    log?.warn?.({ stem, lang, err: err.message }, 'oceanoflights: fetch failed');
    cache.set(key, null);
    return null;
  }
}

// A .docx opens with title/author/section lines before the text proper. They are short, repeat across every
// file, and would align against our headings — so they are dropped rather than offered to the matcher.
const isFrontMatter = (t, i) => i < 6 && t.length < 60;

/** Numbered-verse prefix the site adds ("1 - "), which our copy does not carry. Pure. */
const stripVerseNumber = (t) => String(t).replace(/^\s*\d+\s*[-–—]\s*/, '').replace(/^["“]/, '').trim();

/**
 * Citation the site appends to an Arabic quote — "(الکتاب الأقدس – الفقرة 105)" = Aqdas ¶105, and
 * "الشرح 60" = note 60. A SECOND, independent anchor: verified 2026-08-26 that the quote cited as Aqdas
 * paragraph 105 is paragraph_index 107 in our doc 21307, and that the site's English for it is verbatim
 * ours. Two agreeing signals (citation number + English text) is what a binding should require here.
 */
export function parseCitation(text) {
  const m = String(text || '').match(/[（(]\s*([^)）]*?)\s*[–—-]\s*(الفقرة|الشرح|paragraph|note)\s*(\d+)/i);
  return m ? { work: m[1].trim(), kind: /شرح|note/i.test(m[2]) ? 'note' : 'paragraph', n: Number(m[3]) } : null;
}

/**
 * Build parallel [{ en, source, lang }] rows for one stem, pairing by POSITION within the file.
 *
 * ⚠ MEASURED LIMIT (2026-08-26): position is NOT reliable for every stem. On the Aqdas stem the English
 * file holds 17 paragraphs and the Arabic 14 — the two arrange quotes and House-of-Justice notes under
 * different headings, so the Nth English paragraph is not the Nth Arabic one. The length guard below
 * catches that and abandons the stem rather than binding an offset pairing, which would attach one
 * passage's original to another's text — the one error that cannot be detected afterwards.
 *
 * So this pairs only the stems where the two files genuinely run parallel. Reaching the rest needs the
 * citation anchor (parseCitation) rather than position; that rule is NOT yet written, and until it is,
 * a refused stem is the correct outcome.
 */
export function pairStem(enParas, srcParas) {
  const en = enParas.filter((t, i) => !isFrontMatter(t, i)).map(stripVerseNumber);
  const src = srcParas.filter((t, i) => !isFrontMatter(t, i)).map(stripVerseNumber);
  if (!en.length || en.length !== src.length) return [];
  return en.map((t, i) => ({ en: t, source: src[i], lang: detectSourceLang(src[i]) }))
    .filter((r) => r.lang);                       // a "source" that is not Arabic script is not the original
}

/**
 * Find, for one of OUR documents, the original text of as many paragraphs as possible.
 *
 * `ours` is [{ key, text }]. Returns the rows the caller should persist, plus the stats that say how much of
 * the book was reached — never a bare count, so a thin result is visible as thin.
 */
export async function originalsForDoc(ours, stems, { log, minScore = 0.7, cache = new Map(), onProgress } = {}) {
  const parallel = [];
  let fetched = 0, served = 0;
  for (const stem of stems) {
    const en = await fetchStem(stem, 'en', { log, cache });
    fetched++;
    onProgress?.(fetched, stems.length);
    if (!en?.length) continue;
    for (const lang of ['ar', 'fa']) {
      const src = await fetchStem(stem, lang, { log, cache });
      if (!src?.length) continue;
      const rows = pairStem(en, src);
      if (rows.length) { served++; parallel.push(...rows.map((r) => ({ ...r, stem }))); break; }
    }
  }
  if (!parallel.length) return { matches: [], stats: { stems: stems.length, fetched, served, parallel: 0, matched: 0 } };

  // ENGLISH-to-ENGLISH against our own copy — the same length-aware, monotonic alignment used for CTAI.
  // Their English and ours are frequently the SAME published translation (verified verbatim on the Aqdas),
  // which is why this half is reliable where cross-lingual retrieval was not.
  const theirs = parallel.map((p, i) => ({ key: i, text: p.en }));
  const { matches, stats } = alignSequences(ours, theirs, { minScore, window: theirs.length });
  return {
    matches: matches.map((m) => ({
      ourKey: m.ourKey, score: m.score,
      originalText: parallel[m.theirKey].source,
      originalLang: parallel[m.theirKey].lang,
      stem: parallel[m.theirKey].stem,
    })),
    stats: { stems: stems.length, fetched, served, parallel: parallel.length, matched: matches.length, ...stats },
  };
}
