// concepts/oceanoflights — use oceanoflights.org as a RESEARCH SOURCE to find the original-language text
// parallel to a translation we already hold, so we can enrich OUR document with it.
//
// Chad, 2026-08-26: "I did not say to replace our content with oceanoflights… I just said to use it as a
// research point to find the parallel content." Nothing here ingests, replaces, or re-points a document.
// The only thing written is `original_text` (+ lang, provenance) on paragraphs we already own.
//
// ── WHY THIS WORKS: THE SITE IS A PARALLEL CORPUS, AND ITS FILENAMES SAY SO ──────────────────────────────
// Each passage exists per language under one stem:
//     001-for-interpretation-of-the-holy-writings_en.docx
//     001-for-interpretation-of-the-holy-writings_ar.docx
// So the hard half of the problem — deciding which Arabic text corresponds to which English — is answered
// by the source itself, deterministically. What remains on our side is ENGLISH-to-ENGLISH matching against
// our own copy, which is the alignment already proven at 99% on the CTAI works.
//
// This matters because it reaches the books CTAI cannot: CTAI is a concordance of Shoghi Effendi's
// renderings, so the Kitáb-i-Aqdas, Some Answered Questions and the Tablets of the Divine Plan are absent
// from it — and those are precisely the works where the original carries the MOST weight, because their
// English is not his and fixes no sense (Chad, 2026-08-25).
//
// ⚠ THE SCRAPED PAGES IN OUR CORPUS ARE NAVIGATION CHROME, NOT TEXT. All 66,000 of them hold "Content"
// plus links to `/file/autogenerated/<stem>_<lang>.docx`. Measured 2026-08-26 — reading them as scripture
// yields a table of markdown links. The stems are the only thing worth taking from them; the text has to
// come from the linked file.
// Deps: jszip (docx is a zip), align.js (pure), global fetch.

import { alignSequences, detectSourceLang } from './align.js';

const BASE = 'https://oceanoflights.org/file/autogenerated';
const TIMEOUT_MS = 45000;

/** Strip the language suffix from a scraped path to get the stem shared across languages. Pure. */
export function stemOf(filePath) {
  const base = String(filePath || '').split('/').pop() || '';
  const m = base.match(/-(ar|en|fa|es|fr|de|pt|ru|zh|he|tr|ur|hi)-?\.md$/);
  return m ? base.slice(0, m.index) : null;
}

/** Paragraphs of one .docx, in order. Pure given the buffer. */
export async function docxParagraphs(buf) {
  const JSZip = (await import('jszip')).default;
  const zip = await JSZip.loadAsync(buf);
  const xml = await zip.file('word/document.xml')?.async('string');
  if (!xml) return [];
  const out = [];
  for (const m of xml.match(/<w:p[ >][\s\S]*?<\/w:p>/g) || []) {
    const text = (m.match(/<w:t[^>]*>([\s\S]*?)<\/w:t>/g) || [])
      .map((t) => t.replace(/<[^>]+>/g, ''))
      .join('')
      .replace(/&quot;/g, '"').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
      .replace(/\s+/g, ' ').trim();
    if (text) out.push(text);
  }
  return out;
}

/**
 * Fetch one language of one stem. Returns null when the site does not serve it — which is ordinary, not an
 * error: many passages exist in English only.
 */
export async function fetchStem(stem, lang, { log, cache = new Map() } = {}) {
  const key = `${stem}_${lang}`;
  if (cache.has(key)) return cache.get(key);
  try {
    const res = await fetch(`${BASE}/${key}.docx`, { signal: AbortSignal.timeout(TIMEOUT_MS) });
    if (!res.ok) { cache.set(key, null); return null; }
    const paras = await docxParagraphs(Buffer.from(await res.arrayBuffer()));
    cache.set(key, paras);
    return paras;
  } catch (err) {
    log?.warn?.({ stem, lang, err: err.message }, 'oceanoflights: fetch failed');
    cache.set(key, null);
    return null;
  }
}

// A .docx opens with title/author/section lines before the text proper. They are short, repeat across every
// file, and would align against our headings — so they are dropped rather than offered to the matcher.
const isFrontMatter = (t, i) => i < 6 && t.length < 60;

/** Numbered-verse prefix the site adds ("1 - "), which our copy does not carry. Pure. */
const stripVerseNumber = (t) => String(t).replace(/^\s*\d+\s*[-–—]\s*/, '').replace(/^["“]/, '').trim();

/**
 * Citation the site appends to an Arabic quote — "(الکتاب الأقدس – الفقرة 105)" = Aqdas ¶105, and
 * "الشرح 60" = note 60. A SECOND, independent anchor: verified 2026-08-26 that the quote cited as Aqdas
 * paragraph 105 is paragraph_index 107 in our doc 21307, and that the site's English for it is verbatim
 * ours. Two agreeing signals (citation number + English text) is what a binding should require here.
 */
export function parseCitation(text) {
  const m = String(text || '').match(/[（(]\s*([^)）]*?)\s*[–—-]\s*(الفقرة|الشرح|paragraph|note)\s*(\d+)/i);
  return m ? { work: m[1].trim(), kind: /شرح|note/i.test(m[2]) ? 'note' : 'paragraph', n: Number(m[3]) } : null;
}

/**
 * Build parallel [{ en, source, lang }] rows for one stem by POSITION on the RAW paragraph lists.
 *
 * Chad, 2026-08-26: "Each book in English should have parallel printing in Arabic/Farsi with the originals
 * even broken into the same paragraphing." Verified: the two files run index-for-index — heading pairs with
 * heading, author with author, and body paragraph N with body paragraph N.
 *
 * ⚠ MY EARLIER BUG, AND WHY THIS FILTERS LAST. A first version dropped "short" paragraphs from BOTH sides
 * using one character threshold, then required the survivors to match in count. Arabic is more compact than
 * its English rendering, so the Arabic of a passage routinely fell BELOW the threshold while its English sat
 * above it — the filter manufactured the mismatch it was then used to detect, and refused 31 of 40 stems
 * whose raw lists matched exactly. Pair FIRST on the raw lists, and only then decide which pairs are body
 * text; never let a length rule run independently on two languages that encode length differently.
 */
const NON_BODY = /^(—\s*\d+\s*—|[\d٠-٩]+|نسخه اصل فارسی|Translated|Provisional translation)$/i;

export function pairStem(enParas, srcParas, { minBody = 60 } = {}) {
  if (!enParas?.length || enParas.length !== srcParas?.length) return [];
  const out = [];
  for (let i = 0; i < enParas.length; i++) {
    const en = stripVerseNumber(enParas[i]);
    const source = stripVerseNumber(srcParas[i]);
    const lang = detectSourceLang(source);
    // Keep a pair only when the source really is original-language text and the English side is a passage
    // rather than an author line, a section number, or a "Provisional translation" marker.
    if (!lang || en.length < minBody || NON_BODY.test(en) || detectSourceLang(en)) continue;
    out.push({ en, source, lang });
  }
  return out;
}

/**
 * Find, for one of OUR documents, the original text of as many paragraphs as possible.
 *
 * `ours` is [{ key, text }]. Returns the rows the caller should persist, plus the stats that say how much of
 * the book was reached — never a bare count, so a thin result is visible as thin.
 */
export async function originalsForDoc(ours, stems, { log, minScore = 0.7, cache = new Map(), concurrency = 8 } = {}) {
  // POOLED, and for the same reason the CTAI fetch is pooled: 237 stems at ~1s each is four minutes
  // sequential, which is past the edge proxy's request timeout — the caller gets a 524 and the work is lost
  // with no result and no error. I fixed exactly this for CTAI and then re-introduced it here by writing
  // this path serially (2026-08-26). Concurrency brings a whole book inside one request.
  const results = new Array(stems.length);
  let next = 0;
  const worker = async () => {
    while (next < stems.length) {
      const i = next++;
      const stem = stems[i];
      const en = await fetchStem(stem, 'en', { log, cache });
      if (!en?.length) { results[i] = null; continue; }
      let rows = [];
      for (const lang of ['ar', 'fa']) {
        const src = await fetchStem(stem, lang, { log, cache });
        if (!src?.length) continue;
        rows = pairStem(en, src);
        if (rows.length) break;
      }
      results[i] = rows.length ? rows.map((r) => ({ ...r, stem })) : null;
    }
  };
  await Promise.all(Array.from({ length: Math.min(concurrency, stems.length) }, worker));

  // Order is restored by STEM ORDER, not completion order: the alignment that consumes these is a monotonic
  // sequence match, so shuffled input would break the one property keeping the book in register.
  const parallel = results.filter(Boolean).flat();
  const served = results.filter(Boolean).length;
  const fetched = stems.length;

  if (!parallel.length) return { matches: [], stats: { stems: stems.length, fetched, served, parallel: 0, matched: 0 } };

  // ENGLISH-to-ENGLISH against our own copy — the same length-aware, monotonic alignment used for CTAI.
  // Their English and ours are frequently the SAME published translation (verified verbatim on the Aqdas),
  // which is why this half is reliable where cross-lingual retrieval was not.
  const theirs = parallel.map((p, i) => ({ key: i, text: p.en }));
  const { matches, stats } = alignSequences(ours, theirs, { minScore, window: theirs.length });
  return {
    matches: matches.map((m) => ({
      ourKey: m.ourKey, score: m.score,
      originalText: parallel[m.theirKey].source,
      originalLang: parallel[m.theirKey].lang,
      stem: parallel[m.theirKey].stem,
    })),
    stats: { stems: stems.length, fetched, served, parallel: parallel.length, matched: matches.length, ...stats },
  };
}
