// Migration runner — combines split version files (v1-v25, v26-v45, v46-v58)
// into a single dispatch table, runs pending content + user migrations, and
// owns the _schema_version / _user_schema_version bookkeeping.
//
// Generated by the Phase 4 refactor split of the original api/lib/migrations.js.

import { query, queryOne, userQuery, userQueryOne } from '../db.js';
import { logger } from '../logger.js';

import { migrations as v1to25 } from './v1-v25.js';
import { migrations as v26to45 } from './v26-v45.js';
import { migrations as v46to58 } from './v46-v58.js';
import { userMigrations, USER_DB_CURRENT_VERSION } from './user.js';

// Combined dispatch table — version => async () => void
export const migrations = { ...v1to25, ...v26to45, ...v46to58 };
export const CURRENT_VERSION = 70;
export { USER_DB_CURRENT_VERSION, userMigrations };

/** Get current schema version (content DB) */
async function getSchemaVersion() {
  try {
    const table = await queryOne(`SELECT name FROM sqlite_master WHERE type='table' AND name='_schema_version'`);
    if (!table) return 0;
    const row = await queryOne('SELECT version FROM _schema_version LIMIT 1');
    return row?.version || 0;
  } catch {
    return 0;
  }
}

/** Set schema version (content DB) */
async function setSchemaVersion(version) {
  await query(`CREATE TABLE IF NOT EXISTS _schema_version (version INTEGER PRIMARY KEY)`);
  await query('DELETE FROM _schema_version');
  await query('INSERT INTO _schema_version (version) VALUES (?)', [version]);
}

/** Get current user database schema version */
async function getUserSchemaVersion() {
  try {
    const table = await userQueryOne(`SELECT name FROM sqlite_master WHERE type='table' AND name='_user_schema_version'`);
    if (!table) return 0;
    const row = await userQueryOne('SELECT version FROM _user_schema_version LIMIT 1');
    return row?.version || 0;
  } catch {
    return 0;
  }
}

/** Set user database schema version */
async function setUserSchemaVersion(version) {
  await userQuery(`CREATE TABLE IF NOT EXISTS _user_schema_version (version INTEGER PRIMARY KEY)`);
  await userQuery('DELETE FROM _user_schema_version');
  await userQuery('INSERT INTO _user_schema_version (version) VALUES (?)', [version]);
}

async function runContentMigrations() {
  const fromVersion = await getSchemaVersion();

  if (fromVersion >= CURRENT_VERSION) {
    logger.debug({ version: fromVersion }, 'Content DB schema up to date');
    return { from: fromVersion, to: fromVersion, applied: 0 };
  }

  logger.info({ from: fromVersion, to: CURRENT_VERSION }, 'Running content DB migrations');
  let applied = 0;
  for (let v = fromVersion + 1; v <= CURRENT_VERSION; v++) {
    const migration = migrations[v];
    if (!migration) {
      logger.warn({ version: v }, 'Migration version not defined, skipping');
      continue;
    }
    try {
      logger.info({ version: v }, `Applying content migration ${v}`);
      await migration();
      await setSchemaVersion(v);
      applied++;
    } catch (err) {
      logger.error({ version: v, err: err.message }, `Migration ${v} failed`);
      throw err;
    }
  }

  logger.info({ from: fromVersion, to: CURRENT_VERSION, applied }, 'Content DB migrations complete');
  return { from: fromVersion, to: CURRENT_VERSION, applied };
}

async function runUserMigrations() {
  const fromVersion = await getUserSchemaVersion();

  if (fromVersion >= USER_DB_CURRENT_VERSION) {
    logger.debug({ version: fromVersion }, 'User DB schema up to date');
    return { from: fromVersion, to: fromVersion, applied: 0 };
  }

  logger.info({ from: fromVersion, to: USER_DB_CURRENT_VERSION }, 'Running user DB migrations');
  let applied = 0;
  for (let v = fromVersion + 1; v <= USER_DB_CURRENT_VERSION; v++) {
    const migration = userMigrations[v];
    if (!migration) {
      logger.warn({ version: v }, 'User migration version not defined, skipping');
      continue;
    }
    try {
      logger.info({ version: v }, `Applying user migration ${v}`);
      await migration();
      await setUserSchemaVersion(v);
      applied++;
    } catch (err) {
      logger.error({ version: v, err: err.message }, `User migration ${v} failed`);
      throw err;
    }
  }

  logger.info({ from: fromVersion, to: USER_DB_CURRENT_VERSION, applied }, 'User DB migrations complete');
  return { from: fromVersion, to: USER_DB_CURRENT_VERSION, applied };
}

/**
 * SQL string for migration 44: Layered Indexing Tables.
 * Exported for testing — allows schema verification against an in-memory DB.
 */
export function getMigration44SQL() {
  return `
CREATE TABLE IF NOT EXISTS content_objects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  content_id INTEGER NOT NULL,
  doc_id INTEGER NOT NULL,
  people_json TEXT,
  places_json TEXT,
  documents_json TEXT,
  events_json TEXT,
  concepts_json TEXT,
  relations_json TEXT,
  rendered TEXT,
  object_pipeline_version TEXT NOT NULL DEFAULT 'v1',
  content_hash TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(content_id, object_pipeline_version)
);

CREATE TABLE IF NOT EXISTS content_enrichment (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  content_id INTEGER NOT NULL,
  doc_id INTEGER NOT NULL,
  task_mode TEXT NOT NULL,
  result TEXT,
  instructions_hash TEXT,
  book_meta_hash TEXT,
  window_hash TEXT,
  objects_hash TEXT,
  target_paragraph_id INTEGER,
  pipeline_version TEXT NOT NULL DEFAULT 'v1',
  model_id TEXT,
  prompt_tokens INTEGER,
  cached_tokens INTEGER,
  completion_tokens INTEGER,
  call_ms INTEGER,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(content_id, task_mode, pipeline_version)
);

CREATE TABLE IF NOT EXISTS pipeline_versions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pipeline_name TEXT NOT NULL,
  version TEXT NOT NULL,
  prompt_hash TEXT,
  model_id TEXT,
  config_json TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  active INTEGER DEFAULT 0,
  UNIQUE(pipeline_name, version)
);

CREATE TABLE IF NOT EXISTS pipeline_jobs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  job_type TEXT NOT NULL,
  doc_id INTEGER,
  layer TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  pipeline_version TEXT,
  total_items INTEGER DEFAULT 0,
  completed_items INTEGER DEFAULT 0,
  failed_items INTEGER DEFAULT 0,
  error TEXT,
  worker_id TEXT,
  started_at TEXT,
  completed_at TEXT,
  heartbeat_at TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  config_json TEXT
);

CREATE TABLE IF NOT EXISTS layer_sync_state (
  content_id INTEGER NOT NULL,
  layer TEXT NOT NULL,
  synced INTEGER DEFAULT 0,
  meili_index TEXT,
  synced_at TEXT,
  PRIMARY KEY (content_id, layer)
);

CREATE INDEX IF NOT EXISTS idx_co_doc ON content_objects(doc_id);
CREATE INDEX IF NOT EXISTS idx_co_content ON content_objects(content_id);
CREATE INDEX IF NOT EXISTS idx_ce_doc ON content_enrichment(doc_id);
CREATE INDEX IF NOT EXISTS idx_ce_content ON content_enrichment(content_id);
CREATE INDEX IF NOT EXISTS idx_pj_status ON pipeline_jobs(status);
CREATE INDEX IF NOT EXISTS idx_pj_doc ON pipeline_jobs(doc_id);
CREATE INDEX IF NOT EXISTS idx_lss_dirty ON layer_sync_state(synced) WHERE synced = 0;
  `;
}

export async function runMigrations() {
  const contentResult = await runContentMigrations();
  const userResult = await runUserMigrations();
  return {
    content: contentResult,
    user: userResult,
    // Backwards compatibility
    from: contentResult.from,
    to: contentResult.to,
    applied: contentResult.applied + userResult.applied
  };
}
