// Migration runner — combines split version files (v1-v25, v26-v45, v46-v58)
// into a single dispatch table, runs pending content + user migrations, and
// owns the _schema_version / _user_schema_version bookkeeping.
//
// Generated by the Phase 4 refactor split of the original api/lib/migrations.js.

import { query, queryOne, userQuery, userQueryOne } from '../db.js';
import { logger } from '../logger.js';

import { migrations as v1to25 } from './v1-v25.js';
import { migrations as v26to45, getMigration44SQL } from './v26-v45.js';
import { migrations as v46to58 } from './v46-v58.js';
import { userMigrations, USER_DB_CURRENT_VERSION } from './user.js';

// Combined dispatch table — version => async () => void
export const migrations = { ...v1to25, ...v26to45, ...v46to58 };
export const CURRENT_VERSION = 71;
export { USER_DB_CURRENT_VERSION, userMigrations, getMigration44SQL };

/** Get current schema version (content DB) */
async function getSchemaVersion() {
  try {
    const table = await queryOne(`SELECT name FROM sqlite_master WHERE type='table' AND name='_schema_version'`);
    if (!table) return 0;
    const row = await queryOne('SELECT version FROM _schema_version LIMIT 1');
    return row?.version || 0;
  } catch {
    return 0;
  }
}

/** Set schema version (content DB) */
async function setSchemaVersion(version) {
  await query(`CREATE TABLE IF NOT EXISTS _schema_version (version INTEGER PRIMARY KEY)`);
  await query('DELETE FROM _schema_version');
  await query('INSERT INTO _schema_version (version) VALUES (?)', [version]);
}

/** Get current user database schema version */
async function getUserSchemaVersion() {
  try {
    const table = await userQueryOne(`SELECT name FROM sqlite_master WHERE type='table' AND name='_user_schema_version'`);
    if (!table) return 0;
    const row = await userQueryOne('SELECT version FROM _user_schema_version LIMIT 1');
    return row?.version || 0;
  } catch {
    return 0;
  }
}

/** Set user database schema version */
async function setUserSchemaVersion(version) {
  await userQuery(`CREATE TABLE IF NOT EXISTS _user_schema_version (version INTEGER PRIMARY KEY)`);
  await userQuery('DELETE FROM _user_schema_version');
  await userQuery('INSERT INTO _user_schema_version (version) VALUES (?)', [version]);
}

async function runContentMigrations() {
  const fromVersion = await getSchemaVersion();

  if (fromVersion >= CURRENT_VERSION) {
    logger.debug({ version: fromVersion }, 'Content DB schema up to date');
    return { from: fromVersion, to: fromVersion, applied: 0 };
  }

  logger.info({ from: fromVersion, to: CURRENT_VERSION }, 'Running content DB migrations');
  let applied = 0;
  for (let v = fromVersion + 1; v <= CURRENT_VERSION; v++) {
    const migration = migrations[v];
    if (!migration) {
      logger.warn({ version: v }, 'Migration version not defined, skipping');
      continue;
    }
    try {
      logger.info({ version: v }, `Applying content migration ${v}`);
      await migration();
      await setSchemaVersion(v);
      applied++;
    } catch (err) {
      logger.error({ version: v, err: err.message }, `Migration ${v} failed`);
      throw err;
    }
  }

  logger.info({ from: fromVersion, to: CURRENT_VERSION, applied }, 'Content DB migrations complete');
  return { from: fromVersion, to: CURRENT_VERSION, applied };
}

async function runUserMigrations() {
  const fromVersion = await getUserSchemaVersion();

  if (fromVersion >= USER_DB_CURRENT_VERSION) {
    logger.debug({ version: fromVersion }, 'User DB schema up to date');
    return { from: fromVersion, to: fromVersion, applied: 0 };
  }

  logger.info({ from: fromVersion, to: USER_DB_CURRENT_VERSION }, 'Running user DB migrations');
  let applied = 0;
  for (let v = fromVersion + 1; v <= USER_DB_CURRENT_VERSION; v++) {
    const migration = userMigrations[v];
    if (!migration) {
      logger.warn({ version: v }, 'User migration version not defined, skipping');
      continue;
    }
    try {
      logger.info({ version: v }, `Applying user migration ${v}`);
      await migration();
      await setUserSchemaVersion(v);
      applied++;
    } catch (err) {
      logger.error({ version: v, err: err.message }, `User migration ${v} failed`);
      throw err;
    }
  }

  logger.info({ from: fromVersion, to: USER_DB_CURRENT_VERSION, applied }, 'User DB migrations complete');
  return { from: fromVersion, to: USER_DB_CURRENT_VERSION, applied };
}


export async function runMigrations() {
  const contentResult = await runContentMigrations();
  const userResult = await runUserMigrations();
  return {
    content: contentResult,
    user: userResult,
    // Backwards compatibility
    from: contentResult.from,
    to: contentResult.to,
    applied: contentResult.applied + userResult.applied
  };
}
