// User database migrations — runs against USER_DATABASE_URL (was Turso cloud,
// now also a local file when USER_DATABASE_URL is unset). These tables hold
// user-facing state: users, forum_posts, donations, conversations, search_log,
// api_subscriptions, api_usage_log.
//
// Generated by the Phase 4 refactor split of the original api/lib/migrations.js.

import { userQuery } from '../db.js';
import { logger } from '../logger.js';

export const USER_DB_CURRENT_VERSION = 6;

export const userMigrations = {
  // Version 1: Create all user tables in user database
  1: async () => {
    // Users table
    await userQuery(`
      CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        email TEXT UNIQUE NOT NULL,
        password_hash TEXT,
        name TEXT,
        tier TEXT DEFAULT 'anonymous',
        email_verified INTEGER DEFAULT 0,
        preferred_language TEXT DEFAULT 'en',
        referral_code TEXT,
        referred_by INTEGER,
        preferences TEXT,
        interests TEXT,
        metadata TEXT,
        approved_at TEXT,
        search_count INTEGER DEFAULT 0,
        auth_provider TEXT DEFAULT 'email',
        stripe_customer_id TEXT,
        deletion_requested_at TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP
      )
    `);

    // Anonymous users table
    await userQuery(`
      CREATE TABLE IF NOT EXISTS anonymous_users (
        id TEXT PRIMARY KEY,
        user_agent TEXT,
        first_seen_at TEXT DEFAULT CURRENT_TIMESTAMP,
        last_seen_at TEXT DEFAULT CURRENT_TIMESTAMP,
        search_count INTEGER DEFAULT 0,
        last_search_query TEXT,
        preferences TEXT,
        interests TEXT,
        converted_to_user_id INTEGER,
        converted_at TEXT,
        unified_to INTEGER,
        FOREIGN KEY (converted_to_user_id) REFERENCES users(id),
        FOREIGN KEY (unified_to) REFERENCES users(id)
      )
    `);

    // Verification codes table
    await userQuery(`
      CREATE TABLE IF NOT EXISTS verification_codes (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER,
        email TEXT NOT NULL,
        code TEXT NOT NULL,
        type TEXT NOT NULL DEFAULT 'email_verification',
        expires_at TEXT NOT NULL,
        used_at TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (user_id) REFERENCES users(id)
      )
    `);

    // Refresh tokens table
    await userQuery(`
      CREATE TABLE IF NOT EXISTS refresh_tokens (
        id TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL,
        expires_at TEXT NOT NULL,
        revoked INTEGER DEFAULT 0,
        revoked_at TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
      )
    `);

    // Forum posts table
    await userQuery(`
      CREATE TABLE IF NOT EXISTS forum_posts (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        title TEXT,
        content TEXT NOT NULL,
        category TEXT DEFAULT 'general',
        author_id INTEGER NOT NULL,
        parent_id INTEGER,
        root_post_id INTEGER,
        depth INTEGER DEFAULT 0,
        upvotes INTEGER DEFAULT 0,
        downvotes INTEGER DEFAULT 0,
        reply_count INTEGER DEFAULT 0,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
        last_activity_at TEXT DEFAULT CURRENT_TIMESTAMP,
        deleted_at TEXT,
        FOREIGN KEY (author_id) REFERENCES users(id),
        FOREIGN KEY (parent_id) REFERENCES forum_posts(id),
        FOREIGN KEY (root_post_id) REFERENCES forum_posts(id)
      )
    `);

    // Forum votes table
    await userQuery(`
      CREATE TABLE IF NOT EXISTS forum_votes (
        user_id INTEGER NOT NULL,
        post_id INTEGER NOT NULL,
        vote INTEGER NOT NULL,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (user_id, post_id),
        FOREIGN KEY (user_id) REFERENCES users(id),
        FOREIGN KEY (post_id) REFERENCES forum_posts(id)
      )
    `);

    // Donations table
    await userQuery(`
      CREATE TABLE IF NOT EXISTS donations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER,
        stripe_session_id TEXT,
        stripe_customer_id TEXT,
        stripe_subscription_id TEXT,
        amount REAL NOT NULL,
        currency TEXT DEFAULT 'usd',
        frequency TEXT NOT NULL,
        tier_id TEXT,
        status TEXT DEFAULT 'pending',
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (user_id) REFERENCES users(id)
      )
    `);

    // Conversations table
    await userQuery(`
      CREATE TABLE IF NOT EXISTS conversations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER NOT NULL,
        title TEXT,
        messages TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (user_id) REFERENCES users(id)
      )
    `);

    // Anonymous conversations table
    await userQuery(`
      CREATE TABLE IF NOT EXISTS anonymous_conversations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        anonymous_user_id TEXT NOT NULL,
        user_id INTEGER,
        title TEXT,
        messages TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (anonymous_user_id) REFERENCES anonymous_users(id),
        FOREIGN KEY (user_id) REFERENCES users(id)
      )
    `);

    // User profiles table
    await userQuery(`
      CREATE TABLE IF NOT EXISTS user_profiles (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id TEXT NOT NULL UNIQUE,
        name TEXT,
        bio TEXT,
        spiritual_background TEXT,
        interests TEXT,
        preferred_sources TEXT,
        metadata TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP
      )
    `);

    // Analytics table
    await userQuery(`
      CREATE TABLE IF NOT EXISTS analytics (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER,
        event_type TEXT NOT NULL,
        details TEXT,
        cost_usd REAL DEFAULT 0,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (user_id) REFERENCES users(id)
      )
    `);

    // Create indexes
    try { await userQuery('CREATE INDEX IF NOT EXISTS idx_users_email ON users(email)'); } catch { /* exists */ }
    try { await userQuery('CREATE INDEX IF NOT EXISTS idx_anonymous_users_converted ON anonymous_users(converted_to_user_id)'); } catch { /* exists */ }
    try { await userQuery('CREATE INDEX IF NOT EXISTS idx_verification_email ON verification_codes(email)'); } catch { /* exists */ }
    try { await userQuery('CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON refresh_tokens(user_id)'); } catch { /* exists */ }
    try { await userQuery('CREATE INDEX IF NOT EXISTS idx_forum_posts_author ON forum_posts(author_id)'); } catch { /* exists */ }
    try { await userQuery('CREATE INDEX IF NOT EXISTS idx_forum_posts_parent ON forum_posts(parent_id)'); } catch { /* exists */ }
    try { await userQuery('CREATE INDEX IF NOT EXISTS idx_forum_posts_root ON forum_posts(root_post_id)'); } catch { /* exists */ }
    try { await userQuery('CREATE INDEX IF NOT EXISTS idx_forum_posts_category ON forum_posts(category)'); } catch { /* exists */ }
    try { await userQuery('CREATE INDEX IF NOT EXISTS idx_forum_votes_post ON forum_votes(post_id)'); } catch { /* exists */ }
    try { await userQuery('CREATE INDEX IF NOT EXISTS idx_donations_user ON donations(user_id)'); } catch { /* exists */ }
    try { await userQuery('CREATE INDEX IF NOT EXISTS idx_conversations_user ON conversations(user_id)'); } catch { /* exists */ }
    try { await userQuery('CREATE INDEX IF NOT EXISTS idx_anon_conversations_user ON anonymous_conversations(anonymous_user_id)'); } catch { /* exists */ }
    try { await userQuery('CREATE INDEX IF NOT EXISTS idx_analytics_user ON analytics(user_id)'); } catch { /* exists */ }
    try { await userQuery('CREATE INDEX IF NOT EXISTS idx_analytics_type ON analytics(event_type)'); } catch { /* exists */ }

    logger.info('User database tables created');
  },

  2: async () => {
    logger.info('Starting user migration 2: search_log table');

    await userQuery(`
      CREATE TABLE IF NOT EXISTS search_log (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        query TEXT NOT NULL,
        user_id INTEGER,
        anonymous_user_id TEXT,
        api_key_id INTEGER,
        result_count INTEGER DEFAULT 0,
        duration_ms INTEGER,
        search_type TEXT DEFAULT 'web',
        filters TEXT,
        ip_country TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
      )
    `);

    await userQuery('CREATE INDEX IF NOT EXISTS idx_search_log_created ON search_log(created_at)');
    await userQuery('CREATE INDEX IF NOT EXISTS idx_search_log_user ON search_log(user_id)');
    await userQuery('CREATE INDEX IF NOT EXISTS idx_search_log_anon ON search_log(anonymous_user_id)');
    await userQuery('CREATE INDEX IF NOT EXISTS idx_search_log_query ON search_log(query)');

    logger.info('User migration 2 complete: search_log table created');
  },

  3: async () => {
    logger.info('Starting user migration 3: api_subscriptions and api_usage_log tables');

    await userQuery(`
      CREATE TABLE IF NOT EXISTS api_subscriptions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER NOT NULL,
        stripe_customer_id TEXT,
        stripe_subscription_id TEXT UNIQUE,
        stripe_subscription_item_id TEXT,
        status TEXT DEFAULT 'active',
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        canceled_at TEXT,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP
      )
    `);

    await userQuery(`
      CREATE TABLE IF NOT EXISTS api_usage_log (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER NOT NULL,
        api_key_id INTEGER NOT NULL,
        search_type TEXT NOT NULL,
        was_cached INTEGER DEFAULT 0,
        billable INTEGER DEFAULT 1,
        reported_to_stripe INTEGER DEFAULT 0,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
      )
    `);

    try { await userQuery('CREATE INDEX IF NOT EXISTS idx_api_subscriptions_user ON api_subscriptions(user_id)'); } catch { /* exists */ }
    try { await userQuery('CREATE INDEX IF NOT EXISTS idx_api_usage_log_user ON api_usage_log(user_id)'); } catch { /* exists */ }
    try { await userQuery('CREATE INDEX IF NOT EXISTS idx_api_usage_log_reported ON api_usage_log(reported_to_stripe)'); } catch { /* exists */ }

    logger.info('User migration 3 complete: api_subscriptions and api_usage_log tables created');
  },

  // Version 4: is_test flag — QA/test accounts are excluded from all admin views and analytics
  4: async () => {
    try { await userQuery('ALTER TABLE users ADD COLUMN is_test INTEGER DEFAULT 0'); } catch { /* exists */ }
    await userQuery(`UPDATE users SET is_test = 1 WHERE email LIKE 'test-%@siftersearch.com'`);
    logger.info('User migration 4 complete: users.is_test added, existing test accounts flagged');
  },

  // Version 5: Google sign-in — profile picture (shown in the nav pill) + stable Google account id
  5: async () => {
    try { await userQuery('ALTER TABLE users ADD COLUMN picture TEXT'); } catch { /* exists */ }
    try { await userQuery('ALTER TABLE users ADD COLUMN google_sub TEXT'); } catch { /* exists */ }
    logger.info('User migration 5 complete: users.picture + users.google_sub added');
  },

  // Version 6: Seeker Companion (PRD §2.2, §6, §7, §8, §10, §11). Relationship lifecycle + consent-scoped
  // memory + premise hypotheses (expiring, never fixed labels) + global dial overrides + the outcome
  // exposure log + course enrollment/progress. In the USER db — per-user interaction data, directly
  // writable by the API (no single-writer bottleneck), sensitive, deletable.
  6: async () => {
    // participant_id = users.id (authed) OR an anonymous session id string. stage = R0..R5/RQ.
    await userQuery(`CREATE TABLE IF NOT EXISTS companion_relationship (
      participant_id TEXT PRIMARY KEY,
      stage TEXT NOT NULL DEFAULT 'R0_SESSION',
      consent_memory INTEGER NOT NULL DEFAULT 0,
      consent_contact INTEGER NOT NULL DEFAULT 0,
      dials_json TEXT NOT NULL DEFAULT '{}',
      last_thread_id TEXT,
      created_at INTEGER DEFAULT (unixepoch()),
      updated_at INTEGER DEFAULT (unixepoch())
    )`);
    // Consent-scoped memory (§7.1). kind: goal|question|source|tension|followup|preference|correction|boundary.
    await userQuery(`CREATE TABLE IF NOT EXISTS companion_memory (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      participant_id TEXT NOT NULL,
      kind TEXT NOT NULL,
      content TEXT NOT NULL,
      thread_id TEXT,
      source_ref TEXT,
      confidence REAL,
      corrected INTEGER NOT NULL DEFAULT 0,
      expires_at INTEGER,
      created_at INTEGER DEFAULT (unixepoch())
    )`);
    await userQuery(`CREATE INDEX IF NOT EXISTS idx_cmemory_participant ON companion_memory(participant_id, kind)`);
    // Premise hypotheses (§6) — expiring, correctable, never a fixed personal label.
    await userQuery(`CREATE TABLE IF NOT EXISTS companion_premise (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      participant_id TEXT NOT NULL,
      statement TEXT NOT NULL,
      category TEXT,
      status TEXT NOT NULL DEFAULT 'hypothesis',
      confidence REAL DEFAULT 0.5,
      context TEXT,
      expires_at INTEGER,
      created_at INTEGER DEFAULT (unixepoch())
    )`);
    await userQuery(`CREATE INDEX IF NOT EXISTS idx_cpremise_participant ON companion_premise(participant_id)`);
    // Global dial overrides set in the admin (§10). Per-dial rows; precedence layer = 'global'.
    await userQuery(`CREATE TABLE IF NOT EXISTS companion_dials_global (
      dial_key TEXT PRIMARY KEY,
      value TEXT NOT NULL,
      updated_by TEXT,
      updated_at INTEGER DEFAULT (unixepoch())
    )`);
    // Outcome/exposure log (§11.1) — reconstruct every answer + its plan. Immutable append.
    await userQuery(`CREATE TABLE IF NOT EXISTS companion_exposure (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      participant_id TEXT,
      thread_id TEXT,
      mode TEXT,
      intervention TEXT,
      challenge_level INTEGER,
      authority_classes TEXT,
      plan_json TEXT,
      policy_version TEXT,
      created_at INTEGER DEFAULT (unixepoch())
    )`);
    await userQuery(`CREATE INDEX IF NOT EXISTS idx_cexposure_participant ON companion_exposure(participant_id, created_at)`);
    // Course enrollment + progress (§8).
    await userQuery(`CREATE TABLE IF NOT EXISTS companion_enrollment (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      participant_id TEXT NOT NULL,
      track_id TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'active',
      started_at INTEGER DEFAULT (unixepoch()),
      UNIQUE(participant_id, track_id)
    )`);
    await userQuery(`CREATE TABLE IF NOT EXISTS companion_progress (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      enrollment_id INTEGER NOT NULL,
      section_id TEXT NOT NULL,
      understood INTEGER NOT NULL DEFAULT 0,
      note TEXT,
      created_at INTEGER DEFAULT (unixepoch())
    )`);
    logger.info('User migration 6 complete: Seeker Companion tables (relationship, memory, premise, dials, exposure, courses)');
  },

  // Version 7: consent provenance. Retention consent now arrives by CONNECTING (Google One Tap): sharing
  // an email is the permission to retain. A consent flag with no recorded source cannot be explained back
  // to the person it belongs to, so record how it was given and when, plus which temporary session was
  // merged in on connect (so a merged relationship can be traced, and unpicked if ever disputed).
  7: async () => {
    for (const col of [
      'consent_source TEXT',        // 'connect' (One Tap / login) | 'explicit' (self-service endpoint)
      'consent_at INTEGER',
      'merged_from TEXT',           // the anonymous session participant_id folded into this account
    ]) {
      try { await userQuery(`ALTER TABLE companion_relationship ADD COLUMN ${col}`); } catch { /* exists */ }
    }
    logger.info('User migration 7 complete: companion_relationship consent provenance (consent_source, consent_at, merged_from)');
  },
};
