// Content DB migrations 26..45 — file-hash uniqueness, slug + redirect
// infrastructure, document_failures, table_counts, embedding cache,
// segmenter/translation tables.
//
// Generated by the Phase 4 refactor split of the original api/lib/migrations.js.

import { query, queryOne, queryAll, userQuery, userQueryOne } from '../db.js';
import { logger } from '../logger.js';
import { generateDocSlug } from '../slug.js';

export const migrations = {

  // Version 26: Add unique constraint on file_hash and ensure relative file_path
  // - file_hash uniqueness prevents duplicate content from being indexed twice
  // - file_path should be relative to basePath for library portability
  26: async () => {
    // Add unique index on file_hash (allows NULL values, only enforces uniqueness on non-NULL)
    try {
      await query(`
        CREATE UNIQUE INDEX IF NOT EXISTS idx_docs_file_hash_unique
        ON docs(file_hash)
        WHERE file_hash IS NOT NULL AND file_hash != ''
      `);
      logger.info('Created unique index on file_hash');
    } catch (err) {
      // If duplicates exist, log warning and skip
      if (err.message.includes('UNIQUE constraint failed')) {
        logger.warn('Cannot create unique index on file_hash - duplicates exist. Run cleanup-duplicates.js first.');
      } else {
        logger.error({ err: err.message }, 'Failed to create file_hash unique index');
      }
    }

    // Convert absolute file_path to relative (remove basePath prefix)
    // This makes the library portable - files can be moved as long as structure is preserved
    const docs = await queryAll(`
      SELECT id, file_path FROM docs
      WHERE file_path IS NOT NULL AND file_path LIKE '/%'
    `);

    if (docs.length > 0) {
      logger.info(`Found ${docs.length} documents with absolute file_path, converting to relative`);

      for (const doc of docs) {
        // Extract relative path by removing common base prefixes
        let relativePath = doc.file_path;

        // Common base path patterns to strip
        const basePrefixes = [
          '/home/chad/ocean-library/',
          '/Users/chad/ocean-library/',
          '/var/lib/siftersearch/library/',
        ];

        for (const prefix of basePrefixes) {
          if (relativePath.startsWith(prefix)) {
            relativePath = relativePath.slice(prefix.length);
            break;
          }
        }

        // If still absolute, try to extract from last known structure pattern
        // Pattern: .../Baha'i/Collection/Author/filename.md
        if (relativePath.startsWith('/')) {
          const match = relativePath.match(/\/(Baha'?i|Buddhism|Christianity|Hinduism|Islam|Judaism|Zoroastrianism)\//i);
          if (match) {
            relativePath = relativePath.slice(relativePath.indexOf(match[0]) + 1);
          }
        }

        if (relativePath !== doc.file_path) {
          await query('UPDATE docs SET file_path = ? WHERE id = ?', [relativePath, doc.id]);
        }
      }

      logger.info(`Converted ${docs.length} absolute paths to relative`);
    }

    logger.info('Migration 26: file_hash uniqueness and relative file_path enforcement');
  },

  // Version 27: Migrate docs.id from TEXT to INTEGER for efficiency
  // This is a major schema change that requires recreating tables
  27: async () => {
    logger.info('Starting migration 27: Convert docs.id from TEXT to INTEGER');

    // Drop any leftover temp tables from failed migrations
    await query('DROP TABLE IF EXISTS docs_new');
    await query('DROP TABLE IF EXISTS content_new');

    // Get current columns in docs table
    const columnsResult = await queryAll("PRAGMA table_info(docs)");
    const existingColumns = new Set(columnsResult.map(c => c.name));

    // Define canonical schema with optional columns
    const requiredColumns = ['file_path', 'file_hash', 'filename', 'title', 'author', 'religion', 'collection', 'language', 'year', 'description', 'paragraph_count', 'source_file', 'cover_url', 'auto_segmented', 'encumbered', 'metadata', 'created_at', 'updated_at'];
    const optionalColumns = ['slug']; // slug exists in production but not in dev

    // Build column list for copy - only include columns that exist
    const columnsToCopy = requiredColumns.filter(c => existingColumns.has(c));
    const hasSlug = existingColumns.has('slug');
    if (hasSlug) columnsToCopy.push('slug');

    logger.info({ columns: columnsToCopy, hasSlug }, 'Detected schema columns');

    // Step 1: Create new docs table with INTEGER PRIMARY KEY
    await query(`
      CREATE TABLE IF NOT EXISTS docs_new (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        old_id TEXT,
        file_path TEXT UNIQUE,
        file_hash TEXT,
        filename TEXT,
        title TEXT,
        author TEXT,
        religion TEXT,
        collection TEXT,
        language TEXT DEFAULT 'en',
        year INTEGER,
        description TEXT,
        paragraph_count INTEGER DEFAULT 0,
        source_file TEXT,
        cover_url TEXT,
        slug TEXT UNIQUE,
        auto_segmented INTEGER DEFAULT 0,
        encumbered INTEGER DEFAULT 0,
        metadata TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP
      )
    `);

    // Step 2: Copy all docs, preserving old_id for reference and mapping
    const destColumns = ['old_id', ...columnsToCopy].join(', ');
    const srcColumns = ['id', ...columnsToCopy].join(', ');
    await query(`INSERT INTO docs_new (${destColumns}) SELECT ${srcColumns} FROM docs`);

    const docCount = await queryOne('SELECT COUNT(*) as count FROM docs_new');
    logger.info({ count: docCount?.count }, 'Copied docs to new table with INTEGER ids');

    // Step 3: Create new content table with INTEGER doc_id
    await query(`
      CREATE TABLE IF NOT EXISTS content_new (
        id TEXT PRIMARY KEY,
        doc_id INTEGER NOT NULL,
        paragraph_index INTEGER NOT NULL,
        text TEXT NOT NULL,
        content_hash TEXT,
        heading TEXT,
        blocktype TEXT DEFAULT 'paragraph',
        translation TEXT,
        translation_segments TEXT,
        context TEXT,
        embedding BLOB,
        embedding_model TEXT,
        synced INTEGER DEFAULT 0,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (doc_id) REFERENCES docs_new(id) ON DELETE CASCADE
      )
    `);

    // Step 4: Copy content with mapped doc_id (join on old_id)
    await query(`
      INSERT INTO content_new (id, doc_id, paragraph_index, text, content_hash, heading, blocktype, translation, translation_segments, context, embedding, embedding_model, synced, created_at, updated_at)
      SELECT c.id, d.id, c.paragraph_index, c.text, c.content_hash, c.heading, c.blocktype, c.translation, c.translation_segments, c.context, c.embedding, c.embedding_model, c.synced, c.created_at, c.updated_at
      FROM content c
      INNER JOIN docs_new d ON d.old_id = c.doc_id
    `);

    const contentCount = await queryOne('SELECT COUNT(*) as count FROM content_new');
    logger.info({ count: contentCount?.count }, 'Copied content with new INTEGER doc_ids');

    // Step 5: Update redirects table doc_id (if exists)
    try {
      await query(`
        UPDATE redirects SET doc_id = (
          SELECT CAST(d.id AS TEXT) FROM docs_new d WHERE d.old_id = redirects.doc_id
        )
        WHERE doc_id IS NOT NULL
      `);
      logger.info('Updated redirects table with new doc_ids');
    } catch (err) {
      logger.debug({ err: err.message }, 'Redirects table update skipped (may not exist)');
    }

    // Step 6: Drop old tables and rename new ones
    await query('DROP TABLE IF EXISTS content');
    await query('DROP TABLE IF EXISTS docs');
    await query('ALTER TABLE docs_new RENAME TO docs');
    await query('ALTER TABLE content_new RENAME TO content');

    // Step 7: Recreate indexes
    await query('CREATE INDEX IF NOT EXISTS idx_docs_file_path ON docs(file_path)');
    await query('CREATE INDEX IF NOT EXISTS idx_docs_file_hash ON docs(file_hash)');
    await query('CREATE INDEX IF NOT EXISTS idx_docs_slug ON docs(slug)');
    await query('CREATE INDEX IF NOT EXISTS idx_docs_religion ON docs(religion)');
    await query('CREATE INDEX IF NOT EXISTS idx_docs_collection ON docs(collection)');
    await query('CREATE INDEX IF NOT EXISTS idx_content_doc ON content(doc_id)');
    await query('CREATE INDEX IF NOT EXISTS idx_content_hash ON content(content_hash)');

    logger.info('Migration 27 complete: docs.id is now INTEGER PRIMARY KEY AUTOINCREMENT');
  },

  // Version 28: Drop old_id column from docs table
  28: async () => {
    logger.info('Starting migration 28: Drop old_id column from docs table');

    // Cleanup any leftover docs_new table from failed migration
    await query('DROP TABLE IF EXISTS docs_new');

    // Step 1: Create new docs table without old_id (matching actual production schema)
    await query(`
      CREATE TABLE IF NOT EXISTS docs_new (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        file_path TEXT UNIQUE,
        file_hash TEXT,
        filename TEXT,
        title TEXT,
        author TEXT,
        religion TEXT,
        collection TEXT,
        language TEXT DEFAULT 'en',
        year INTEGER,
        description TEXT,
        paragraph_count INTEGER DEFAULT 0,
        source_file TEXT,
        cover_url TEXT,
        slug TEXT,
        auto_segmented INTEGER DEFAULT 0,
        encumbered INTEGER DEFAULT 0,
        metadata TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP
      )
    `);

    // Step 2: Copy all docs (excluding old_id)
    await query(`
      INSERT INTO docs_new (id, file_path, file_hash, filename, title, author, religion, collection, language, year, description, paragraph_count, source_file, cover_url, slug, auto_segmented, encumbered, metadata, created_at, updated_at)
      SELECT id, file_path, file_hash, filename, title, author, religion, collection, language, year, description, paragraph_count, source_file, cover_url, slug, auto_segmented, encumbered, metadata, created_at, updated_at
      FROM docs
    `);

    // Step 3: Drop old table and rename new one
    await query('DROP TABLE docs');
    await query('ALTER TABLE docs_new RENAME TO docs');

    // Step 4: Recreate indexes
    await query('CREATE INDEX IF NOT EXISTS idx_docs_file_path ON docs(file_path)');
    await query('CREATE INDEX IF NOT EXISTS idx_docs_file_hash ON docs(file_hash)');
    await query('CREATE INDEX IF NOT EXISTS idx_docs_slug ON docs(slug)');
    await query('CREATE INDEX IF NOT EXISTS idx_docs_religion ON docs(religion)');
    await query('CREATE INDEX IF NOT EXISTS idx_docs_collection ON docs(collection)');

    logger.info('Migration 28 complete: old_id column removed from docs table');
  },

  // Version 29: Add body_hash column for metadata-only updates
  // Allows editing frontmatter (title, author, etc.) without re-processing content
  // file_hash detects ANY file change, body_hash detects CONTENT change only
  29: async () => {
    try {
      await query('ALTER TABLE docs ADD COLUMN body_hash TEXT');
      logger.info('Added body_hash column to docs table');
    } catch (err) {
      if (!err.message.includes('duplicate column')) throw err;
    }

    // Create index for potential future queries by body_hash
    await query('CREATE INDEX IF NOT EXISTS idx_docs_body_hash ON docs(body_hash)');

    logger.info('Migration 29 complete: body_hash column added for metadata-only updates');
  },

  // Version 30: Convert content.id from TEXT to INTEGER
  // Meilisearch already uses rowid as its id - this makes SQLite match
  // Preserves all embeddings and data by copying with rowid as new id
  30: async () => {
    logger.info('Starting migration 30: Convert content.id from TEXT to INTEGER');

    // Check current schema
    const schema = await queryAll("PRAGMA table_info(content)");
    const idColumn = schema.find(c => c.name === 'id');

    if (idColumn && idColumn.type === 'INTEGER') {
      logger.info('content.id is already INTEGER, skipping migration');
      return;
    }

    // Get count for progress logging
    const countResult = await queryOne('SELECT COUNT(*) as count FROM content');
    const totalRows = countResult?.count || 0;
    logger.info({ totalRows }, 'Migrating content table to INTEGER id');

    // Step 1: Create new content table with INTEGER PRIMARY KEY
    // Using AUTOINCREMENT to ensure new IDs continue from highest existing
    await query(`
      CREATE TABLE IF NOT EXISTS content_new (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        doc_id INTEGER NOT NULL,
        paragraph_index INTEGER NOT NULL,
        text TEXT NOT NULL,
        content_hash TEXT,
        heading TEXT,
        blocktype TEXT DEFAULT 'paragraph',
        translation TEXT,
        translation_segments TEXT,
        context TEXT,
        embedding BLOB,
        embedding_model TEXT,
        synced INTEGER DEFAULT 0,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (doc_id) REFERENCES docs(id) ON DELETE CASCADE
      )
    `);

    // Step 2: Copy all data using rowid as the new id
    // This preserves the Meilisearch link since Meili uses rowid
    await query(`
      INSERT INTO content_new (id, doc_id, paragraph_index, text, content_hash, heading, blocktype, translation, translation_segments, context, embedding, embedding_model, synced, created_at, updated_at)
      SELECT rowid, doc_id, paragraph_index, text, content_hash, heading, blocktype, translation, translation_segments, context, embedding, embedding_model, synced, created_at, updated_at
      FROM content
    `);

    const newCount = await queryOne('SELECT COUNT(*) as count FROM content_new');
    logger.info({ originalCount: totalRows, newCount: newCount?.count }, 'Copied content with INTEGER ids');

    // Verify counts match before proceeding
    if (newCount?.count !== totalRows) {
      throw new Error(`Row count mismatch: original ${totalRows}, new ${newCount?.count}`);
    }

    // Step 3: Verify embeddings were preserved (spot check)
    const embeddingCheck = await queryOne(`
      SELECT
        (SELECT COUNT(*) FROM content WHERE embedding IS NOT NULL) as old_count,
        (SELECT COUNT(*) FROM content_new WHERE embedding IS NOT NULL) as new_count
    `);
    logger.info({
      oldEmbeddings: embeddingCheck?.old_count,
      newEmbeddings: embeddingCheck?.new_count
    }, 'Embedding preservation check');

    if (embeddingCheck?.old_count !== embeddingCheck?.new_count) {
      throw new Error(`Embedding count mismatch: original ${embeddingCheck?.old_count}, new ${embeddingCheck?.new_count}`);
    }

    // Step 4: Drop old table and rename new one
    await query('DROP TABLE content');
    await query('ALTER TABLE content_new RENAME TO content');

    // Step 5: Recreate indexes
    await query('CREATE INDEX IF NOT EXISTS idx_content_doc ON content(doc_id)');
    await query('CREATE INDEX IF NOT EXISTS idx_content_hash ON content(content_hash)');
    await query('CREATE INDEX IF NOT EXISTS idx_content_synced ON content(synced)');

    // Step 6: Update sqlite_sequence to ensure AUTOINCREMENT continues correctly
    const maxId = await queryOne('SELECT MAX(id) as max_id FROM content');
    if (maxId?.max_id) {
      await query(`
        INSERT OR REPLACE INTO sqlite_sequence (name, seq)
        VALUES ('content', ?)
      `, [maxId.max_id]);
    }

    logger.info('Migration 30 complete: content.id is now INTEGER PRIMARY KEY AUTOINCREMENT');
  },

  // Version 31: Add soft-delete support for embedding retention
  // Documents and content are soft-deleted (deleted_at set) instead of hard-deleted
  // This preserves embeddings for 30 days to avoid regenerating expensive embeddings
  // when re-importing similar content
  31: async () => {
    logger.info('Starting migration 31: Add soft-delete columns for embedding retention');

    // Add deleted_at to docs table
    try {
      await query('ALTER TABLE docs ADD COLUMN deleted_at TEXT');
      logger.info('Added deleted_at column to docs table');
    } catch (err) {
      if (!err.message?.includes('duplicate column')) {
        throw err;
      }
      logger.info('deleted_at column already exists in docs table');
    }

    // Add deleted_at to content table
    try {
      await query('ALTER TABLE content ADD COLUMN deleted_at TEXT');
      logger.info('Added deleted_at column to content table');
    } catch (err) {
      if (!err.message?.includes('duplicate column')) {
        throw err;
      }
      logger.info('deleted_at column already exists in content table');
    }

    // Create index on deleted_at for efficient filtering
    await query('CREATE INDEX IF NOT EXISTS idx_docs_deleted_at ON docs(deleted_at)');
    await query('CREATE INDEX IF NOT EXISTS idx_content_deleted_at ON content(deleted_at)');

    // Create composite index for embedding lookup by content_hash (includes deleted content)
    // This enables fast embedding reuse across all content including soft-deleted
    await query('CREATE INDEX IF NOT EXISTS idx_content_hash_embedding ON content(content_hash, embedding_model) WHERE embedding IS NOT NULL');

    logger.info('Migration 31 complete: Soft-delete columns added for embedding retention');
  },

  // Version 32: Add normalized_hash for embedding deduplication
  // Enables sharing embeddings across documents with identical content
  // (same paragraph quoted in 50 docs = 1 embedding generation)
  32: async () => {
    logger.info('Starting migration 32: Add normalized_hash for embedding deduplication');

    // Add normalized_hash column to content table
    try {
      await query('ALTER TABLE content ADD COLUMN normalized_hash TEXT');
      logger.info('Added normalized_hash column to content table');
    } catch (err) {
      if (!err.message?.includes('duplicate column')) {
        throw err;
      }
      logger.info('normalized_hash column already exists in content table');
    }

    // Create index for fast embedding lookup by normalized_hash
    // This is the key index for embedding deduplication
    await query('CREATE INDEX IF NOT EXISTS idx_content_normalized_hash ON content(normalized_hash, embedding_model) WHERE embedding IS NOT NULL');

    logger.info('Migration 32 complete: normalized_hash column added for embedding deduplication');
  },

  // Version 33: Mark that normalized_hash backfill is needed
  // The actual backfill is done via admin endpoint since it's a long-running operation (400k+ rows)
  // New content will have normalized_hash computed on insert automatically
  33: async () => {
    logger.info('Migration 33: normalized_hash backfill marker');

    // Check how many need processing
    const countResult = await queryOne('SELECT COUNT(*) as count FROM content WHERE normalized_hash IS NULL AND text IS NOT NULL');
    const totalRows = countResult?.count || 0;

    if (totalRows === 0) {
      logger.info('Migration 33: All content already has normalized_hash');
    } else {
      logger.warn({ totalRows }, 'Migration 33: Content rows need normalized_hash backfill - run POST /api/admin/backfill-normalized-hash');
    }
  },

  // Version 34: Add document_failures table for tracking ingestion failures
  // Documents with oversized paragraphs or other validation errors are logged here
  // instead of being silently accepted with bad data
  34: async () => {
    logger.info('Starting migration 34: Create document_failures table');

    await query(`
      CREATE TABLE IF NOT EXISTS document_failures (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        file_path TEXT,
        file_name TEXT,
        error_type TEXT NOT NULL,
        error_message TEXT NOT NULL,
        details TEXT,
        resolved INTEGER DEFAULT 0,
        resolved_at TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
      )
    `);

    // Create indexes for efficient querying
    await query('CREATE INDEX IF NOT EXISTS idx_doc_failures_resolved ON document_failures(resolved)');
    await query('CREATE INDEX IF NOT EXISTS idx_doc_failures_error_type ON document_failures(error_type)');
    await query('CREATE INDEX IF NOT EXISTS idx_doc_failures_file_path ON document_failures(file_path)');
    await query('CREATE INDEX IF NOT EXISTS idx_doc_failures_created ON document_failures(created_at DESC)');

    logger.info('Migration 34 complete: document_failures table created');
  },

  // Version 35: Add index for embedding worker queries
  // The existing idx_content_normalized_hash only covers rows WITH embeddings
  // We need a partial index for rows NEEDING embeddings (embedding IS NULL)
  35: async () => {
    logger.info('Starting migration 35: Add index for embedding worker');

    // This index optimizes the embedding worker's main query:
    // SELECT ... FROM content WHERE embedding IS NULL AND deleted_at IS NULL
    await query('CREATE INDEX IF NOT EXISTS idx_content_needs_embedding ON content(deleted_at, normalized_hash) WHERE embedding IS NULL');

    logger.info('Migration 35 complete: embedding worker index added');
  },

  // Version 36: Add file_mtime column to docs table
  // Tracks when the source file was last modified for accurate "added" vs "modified" filtering
  36: async () => {
    logger.info('Starting migration 36: Add file_mtime column to docs');

    try {
      await query('ALTER TABLE docs ADD COLUMN file_mtime TEXT');
      logger.info('Added file_mtime column to docs table');
    } catch (err) {
      if (!err.message?.includes('duplicate column')) {
        throw err;
      }
      logger.info('file_mtime column already exists in docs table');
    }

    // Create index for efficient filtering by file modification time
    await query('CREATE INDEX IF NOT EXISTS idx_docs_file_mtime ON docs(file_mtime)');

    logger.info('Migration 36 complete: file_mtime column added');
  },

  37: async () => {
    logger.info('Starting migration 37: API keys table');

    await query(`
      CREATE TABLE IF NOT EXISTS api_keys (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER NOT NULL,
        name TEXT NOT NULL,
        key_hash TEXT UNIQUE NOT NULL,
        key_prefix TEXT NOT NULL,
        rate_limit INTEGER DEFAULT 1000,
        permissions TEXT DEFAULT '["search"]',
        last_used_at TEXT,
        request_count INTEGER DEFAULT 0,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        revoked_at TEXT
      )
    `);

    await query('CREATE INDEX IF NOT EXISTS idx_api_keys_hash ON api_keys(key_hash)');
    await query('CREATE INDEX IF NOT EXISTS idx_api_keys_user ON api_keys(user_id)');

    logger.info('Migration 37 complete: api_keys table created');
  },

  38: async () => {
    logger.info('Starting migration 38: sync_jobs table');

    await query(`
      CREATE TABLE IF NOT EXISTS sync_jobs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        job_type TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'pending',
        total_items INTEGER DEFAULT 0,
        completed_items INTEGER DEFAULT 0,
        failed_items INTEGER DEFAULT 0,
        created_at TEXT DEFAULT (datetime('now')),
        started_at TEXT,
        completed_at TEXT,
        error TEXT
      )
    `);

    await query('CREATE INDEX IF NOT EXISTS idx_sync_jobs_status ON sync_jobs(status, created_at)');

    logger.info('Migration 38 complete: sync_jobs table created');
  },

  // Migration 39: Counter table for instant COUNT queries
  // Replaces expensive COUNT(*) on 2.5M row content table (~2.2s each) with instant lookups
  39: async () => {
    logger.info('Starting migration 39: table_counts + triggers');

    // Create the counter table
    await query(`
      CREATE TABLE IF NOT EXISTS table_counts (
        table_name TEXT PRIMARY KEY,
        row_count INTEGER NOT NULL DEFAULT 0
      )
    `);

    // Seed with current counts (one-time expensive operation during migration)
    const docsCount = await queryOne('SELECT COUNT(*) as c FROM docs WHERE deleted_at IS NULL');
    const contentCount = await queryOne('SELECT COUNT(*) as c FROM content WHERE deleted_at IS NULL');
    const unsyncedCount = await queryOne('SELECT COUNT(*) as c FROM content WHERE synced = 0 AND deleted_at IS NULL');
    const docsWithContentCount = await queryOne('SELECT COUNT(DISTINCT doc_id) as c FROM content WHERE deleted_at IS NULL');

    await query(`INSERT OR REPLACE INTO table_counts (table_name, row_count) VALUES ('docs', ?)`, [docsCount?.c || 0]);
    await query(`INSERT OR REPLACE INTO table_counts (table_name, row_count) VALUES ('content', ?)`, [contentCount?.c || 0]);
    await query(`INSERT OR REPLACE INTO table_counts (table_name, row_count) VALUES ('content_unsynced', ?)`, [unsyncedCount?.c || 0]);
    await query(`INSERT OR REPLACE INTO table_counts (table_name, row_count) VALUES ('docs_with_content', ?)`, [docsWithContentCount?.c || 0]);

    // --- Triggers for docs table ---
    await query(`
      CREATE TRIGGER IF NOT EXISTS trg_docs_insert AFTER INSERT ON docs
      WHEN NEW.deleted_at IS NULL
      BEGIN
        UPDATE table_counts SET row_count = row_count + 1 WHERE table_name = 'docs';
      END
    `);

    await query(`
      CREATE TRIGGER IF NOT EXISTS trg_docs_soft_delete AFTER UPDATE OF deleted_at ON docs
      WHEN OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL
      BEGIN
        UPDATE table_counts SET row_count = MAX(0, row_count - 1) WHERE table_name = 'docs';
      END
    `);

    await query(`
      CREATE TRIGGER IF NOT EXISTS trg_docs_undelete AFTER UPDATE OF deleted_at ON docs
      WHEN OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS NULL
      BEGIN
        UPDATE table_counts SET row_count = row_count + 1 WHERE table_name = 'docs';
      END
    `);

    // --- Triggers for content table ---
    await query(`
      CREATE TRIGGER IF NOT EXISTS trg_content_insert AFTER INSERT ON content
      WHEN NEW.deleted_at IS NULL
      BEGIN
        UPDATE table_counts SET row_count = row_count + 1 WHERE table_name = 'content';
        UPDATE table_counts SET row_count = row_count + 1 WHERE table_name = 'content_unsynced' AND NEW.synced = 0;
      END
    `);

    await query(`
      CREATE TRIGGER IF NOT EXISTS trg_content_soft_delete AFTER UPDATE OF deleted_at ON content
      WHEN OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL
      BEGIN
        UPDATE table_counts SET row_count = MAX(0, row_count - 1) WHERE table_name = 'content';
        UPDATE table_counts SET row_count = MAX(0, row_count - 1) WHERE table_name = 'content_unsynced' AND OLD.synced = 0;
      END
    `);

    await query(`
      CREATE TRIGGER IF NOT EXISTS trg_content_undelete AFTER UPDATE OF deleted_at ON content
      WHEN OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS NULL
      BEGIN
        UPDATE table_counts SET row_count = row_count + 1 WHERE table_name = 'content';
        UPDATE table_counts SET row_count = row_count + 1 WHERE table_name = 'content_unsynced' AND NEW.synced = 0;
      END
    `);

    // Track synced status changes
    await query(`
      CREATE TRIGGER IF NOT EXISTS trg_content_synced AFTER UPDATE OF synced ON content
      WHEN OLD.synced = 0 AND NEW.synced = 1 AND NEW.deleted_at IS NULL
      BEGIN
        UPDATE table_counts SET row_count = MAX(0, row_count - 1) WHERE table_name = 'content_unsynced';
      END
    `);

    await query(`
      CREATE TRIGGER IF NOT EXISTS trg_content_unsynced AFTER UPDATE OF synced ON content
      WHEN OLD.synced = 1 AND NEW.synced = 0 AND NEW.deleted_at IS NULL
      BEGIN
        UPDATE table_counts SET row_count = row_count + 1 WHERE table_name = 'content_unsynced';
      END
    `);

    // Track docs_with_content: increment when first content row inserted for a doc
    await query(`
      CREATE TRIGGER IF NOT EXISTS trg_content_insert_doc_count AFTER INSERT ON content
      WHEN NEW.deleted_at IS NULL
        AND (SELECT COUNT(*) FROM content WHERE doc_id = NEW.doc_id AND deleted_at IS NULL AND id != NEW.id) = 0
      BEGIN
        UPDATE table_counts SET row_count = row_count + 1 WHERE table_name = 'docs_with_content';
      END
    `);

    // Decrement when last content row for a doc is soft-deleted
    await query(`
      CREATE TRIGGER IF NOT EXISTS trg_content_delete_doc_count AFTER UPDATE OF deleted_at ON content
      WHEN OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL
        AND (SELECT COUNT(*) FROM content WHERE doc_id = NEW.doc_id AND deleted_at IS NULL) = 0
      BEGIN
        UPDATE table_counts SET row_count = MAX(0, row_count - 1) WHERE table_name = 'docs_with_content';
      END
    `);

    logger.info({
      docs: docsCount?.c,
      content: contentCount?.c,
      unsynced: unsyncedCount?.c,
      docsWithContent: docsWithContentCount?.c
    }, 'Migration 39 complete: table_counts seeded with triggers');
  },

  40: async () => {
    logger.info('Starting migration 40: embedding counters + triggers for single-writer architecture');

    // NOTE: Index creation deferred — CREATE INDEX scans the full 17GB table,
    // causing D-state hangs on swap-starved servers. Run manually when memory frees up:
    //   CREATE INDEX IF NOT EXISTS idx_content_unsynced_partial ON content(synced, deleted_at) WHERE synced = 0 AND deleted_at IS NULL;
    //   CREATE INDEX IF NOT EXISTS idx_content_needs_embedding_v2 ON content(embedding, deleted_at, id) WHERE embedding IS NULL AND deleted_at IS NULL;

    // Seed counter table with embedding-related counts (extends migration 39 pattern)
    // Use 0 as placeholder — triggers maintain correct counts from here on.
    await query(`INSERT OR REPLACE INTO table_counts (table_name, row_count) VALUES ('content_unembedded', 0)`);
    await query(`INSERT OR REPLACE INTO table_counts (table_name, row_count) VALUES ('content_oversized', 0)`);

    // Triggers for embedding counter: decrement when embedding is set, increment when cleared
    await query(`
      CREATE TRIGGER IF NOT EXISTS trg_content_embedding_set AFTER UPDATE OF embedding ON content
      WHEN OLD.embedding IS NULL AND NEW.embedding IS NOT NULL AND NEW.deleted_at IS NULL
      BEGIN
        UPDATE table_counts SET row_count = MAX(0, row_count - 1) WHERE table_name = 'content_unembedded';
      END
    `);

    await query(`
      CREATE TRIGGER IF NOT EXISTS trg_content_embedding_clear AFTER UPDATE OF embedding ON content
      WHEN OLD.embedding IS NOT NULL AND NEW.embedding IS NULL AND NEW.deleted_at IS NULL
      BEGIN
        UPDATE table_counts SET row_count = row_count + 1 WHERE table_name = 'content_unembedded';
      END
    `);

    logger.info('Migration 40 complete: composite indexes + embedding counters (seeded with 0)');
  },

  41: async () => {
    logger.info('Starting migration 41: librarian_suggestions table');

    await query(`
      CREATE TABLE IF NOT EXISTS librarian_suggestions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        type TEXT NOT NULL,
        data TEXT NOT NULL,
        priority TEXT DEFAULT 'medium',
        status TEXT DEFAULT 'pending',
        admin_notes TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        reviewed_at TEXT
      )
    `);

    await query(`CREATE INDEX IF NOT EXISTS idx_librarian_suggestions_status ON librarian_suggestions(status)`);

    logger.info('Migration 41 complete: librarian_suggestions table');
  },

  42: async () => {
    logger.info('Starting migration 42: backfill empty doc slugs');

    const docs = await queryAll(`
      SELECT id, title, author, filename, language
      FROM docs
      WHERE (slug IS NULL OR slug = '') AND title IS NOT NULL
    `);

    let updated = 0;
    const seen = new Set();
    // Collect existing slugs to avoid collisions
    const existing = await queryAll(`SELECT slug FROM docs WHERE slug IS NOT NULL AND slug != ''`);
    for (const row of existing) seen.add(row.slug);

    for (const doc of docs) {
      let slug = generateDocSlug(doc);
      if (!slug) continue;

      // Ensure uniqueness
      if (seen.has(slug)) {
        let counter = 2;
        while (seen.has(`${slug}-${counter}`)) counter++;
        slug = `${slug}-${counter}`;
      }

      await query(`UPDATE docs SET slug = ? WHERE id = ?`, [slug, doc.id]);
      seen.add(slug);
      updated++;
    }

    logger.info({ total: docs.length, updated }, 'Migration 42 complete: backfilled doc slugs');
  },

  // Version 43: RAG Enhancement Layer — new columns + doc_entities table + indexes
  43: async () => {
    logger.info('Starting migration 43: RAG enhancement layer schema');
    // New content columns for enhancement pipeline
    try { await query('ALTER TABLE content ADD COLUMN hyp_questions TEXT'); } catch (err) {
      if (!err.message?.includes('duplicate column')) throw err;
    }
    try { await query('ALTER TABLE content ADD COLUMN context_model TEXT'); } catch (err) {
      if (!err.message?.includes('duplicate column')) throw err;
    }
    try { await query('ALTER TABLE content ADD COLUMN enhanced_synced INTEGER DEFAULT 0'); } catch (err) {
      if (!err.message?.includes('duplicate column')) throw err;
    }
    // Optional tier column on docs (may already exist)
    try {
      await query("ALTER TABLE docs ADD COLUMN tier TEXT DEFAULT 'secondary'");
    } catch { /* column may exist */ }
    // Entity store for whole-document NER
    await query(`
      CREATE TABLE IF NOT EXISTS doc_entities (
        doc_id INTEGER PRIMARY KEY,
        entities TEXT NOT NULL,
        model TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (doc_id) REFERENCES docs(id)
      )
    `);
    // Partial indexes for enhancement worker queries
    try { await query('CREATE INDEX IF NOT EXISTS idx_content_needs_context ON content(doc_id, paragraph_index) WHERE context IS NULL AND deleted_at IS NULL'); } catch { /* exists */ }
    try { await query('CREATE INDEX IF NOT EXISTS idx_content_needs_hype ON content(id) WHERE hyp_questions IS NULL AND context IS NOT NULL AND deleted_at IS NULL'); } catch { /* exists */ }
    try { await query('CREATE INDEX IF NOT EXISTS idx_content_enhanced_unsynced ON content(enhanced_synced, deleted_at) WHERE enhanced_synced = 0 AND deleted_at IS NULL'); } catch { /* exists */ }
    logger.info('Migration 43 complete: RAG enhancement layer schema added');
  },

  // Version 44: Layered Indexing Tables
  44: async () => {
    logger.info('Starting migration 44: Layered indexing tables');
    await query(getMigration44SQL());
    logger.info('Migration 44 complete: Layered indexing tables added');
  },
  // Version 45: Normalize religion name from "Buddhism" to "Buddhist"
  // Library was renamed from Buddhism to Buddhist but old docs retained stale value
  45: async () => {
    logger.info('Starting migration 45: Normalize Buddhism → Buddhist');
    await query("UPDATE docs SET religion = 'Buddhist' WHERE religion = 'Buddhism'");
    await query("UPDATE library_nodes SET name = 'Buddhist' WHERE node_type = 'religion' AND name = 'Buddhism'");
    logger.info('Migration 45 complete: Buddhism renamed to Buddhist');
  },
};
