// Content DB migrations 46..67 — partial indexes for embedding migration,
// HyPE/disambiguation columns, doc_pages + published_conversations,
// translation_cache, content.is_duplicate, external-site columns
// (source_site, source_url, duplicate_of, external_para_id, external_id),
// supersession-lookup covering index, deep_research tables, para_meta attribution.
//
// Generated by the Phase 4 refactor split of the original api/lib/migrations.js.

import { query, queryOne, queryAll, userQuery, userQueryOne } from '../db.js';
import { logger } from '../logger.js';
import { generateDocSlug } from '../slug.js';

export const migrations = {
  // Version 46: Add partial indexes for embedding migration and worker queries
  // These enable fast lookups without full table scans on multi-million row tables
  46: async () => {
    logger.info('Starting migration 46: Content table indexes');
    // Check which columns exist (test DBs may not have all columns)
    const cols = (await queryAll(`PRAGMA table_info(content)`)).map(c => c.name);
    if (cols.includes('embedding')) {
      await query(`CREATE INDEX IF NOT EXISTS idx_content_has_embedding
        ON content(id) WHERE embedding IS NOT NULL AND deleted_at IS NULL`);
    }
    if (cols.includes('synced')) {
      await query(`CREATE INDEX IF NOT EXISTS idx_content_unsynced
        ON content(synced) WHERE synced = 0 AND deleted_at IS NULL`);
    }
    if (cols.includes('enhanced_synced')) {
      await query(`CREATE INDEX IF NOT EXISTS idx_content_unsynced_enhanced
        ON content(enhanced_synced) WHERE enhanced_synced = 0 AND deleted_at IS NULL`);
    }
    if (cols.includes('normalized_hash')) {
      await query(`CREATE INDEX IF NOT EXISTS idx_content_normalized_hash
        ON content(normalized_hash) WHERE normalized_hash IS NOT NULL`);
    }
    logger.info('Migration 46 complete: Content table indexes added');
  },
  // Version 47: Add per-paragraph language column
  // Falls back to doc.language when NULL. Enables proper language-specific
  // segmentation and search for mixed-language documents.
  47: async () => {
    logger.info('Starting migration 47: Add language column to content');
    const cols = (await queryAll('PRAGMA table_info(content)')).map(c => c.name);
    if (!cols.includes('language')) {
      await query('ALTER TABLE content ADD COLUMN language TEXT DEFAULT NULL');
    }
    logger.info('Migration 47 complete: language column added to content');
  },
  // Version 48: Add normalized body hash for duplicate detection
  // body_hash is exact (for change detection); body_hash_normalized ignores
  // whitespace, markdown formatting, and punctuation (for dedup).
  // Paragraph-level fingerprinting uses content.normalized_hash directly (no denormalization needed).
  48: async () => {
    logger.info('Starting migration 48: Add body_hash_normalized column');
    const cols = (await queryAll('PRAGMA table_info(docs)')).map(c => c.name);
    if (!cols.includes('body_hash_normalized')) {
      await query('ALTER TABLE docs ADD COLUMN body_hash_normalized TEXT');
      await query('CREATE INDEX IF NOT EXISTS idx_docs_body_hash_norm ON docs(body_hash_normalized) WHERE deleted_at IS NULL');
    }
    logger.info('Migration 48 complete: body_hash_normalized column added to docs');
  },

  // Version 49: Add purchase_url for linking to external purchase pages (Amazon, publisher, etc.)
  49: async () => {
    logger.info('Starting migration 49: Add purchase_url column to docs');
    const cols = (await queryAll('PRAGMA table_info(docs)')).map(c => c.name);
    if (!cols.includes('purchase_url')) {
      await query('ALTER TABLE docs ADD COLUMN purchase_url TEXT');
    }
    logger.info('Migration 49 complete: purchase_url column added to docs');
  },

  // Version 50: Graph entity and relation tables for knowledge graph visualization
  50: async () => {
    logger.info('Starting migration 50: Create graph_entities and graph_relations tables');

    await query(`
      CREATE TABLE IF NOT EXISTS graph_entities (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        canonical_name TEXT NOT NULL,
        entity_type TEXT NOT NULL,
        religion TEXT,
        mention_count INTEGER DEFAULT 1,
        doc_count INTEGER DEFAULT 1,
        era TEXT,
        description TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(canonical_name, entity_type, religion)
      )
    `);

    await query(`
      CREATE TABLE IF NOT EXISTS graph_relations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        source_entity_id INTEGER NOT NULL,
        target_entity_id INTEGER NOT NULL,
        relation_type TEXT NOT NULL DEFAULT 'co-occurs',
        weight INTEGER DEFAULT 1,
        source_doc_id INTEGER,
        source_content_id INTEGER,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(source_entity_id, target_entity_id, relation_type),
        FOREIGN KEY (source_entity_id) REFERENCES graph_entities(id),
        FOREIGN KEY (target_entity_id) REFERENCES graph_entities(id)
      )
    `);

    await query('CREATE INDEX IF NOT EXISTS idx_ge_religion ON graph_entities(religion)');
    await query('CREATE INDEX IF NOT EXISTS idx_ge_type ON graph_entities(entity_type)');
    await query('CREATE INDEX IF NOT EXISTS idx_ge_mention ON graph_entities(mention_count DESC)');
    await query('CREATE INDEX IF NOT EXISTS idx_gr_source ON graph_relations(source_entity_id)');
    await query('CREATE INDEX IF NOT EXISTS idx_gr_target ON graph_relations(target_entity_id)');

    logger.info('Migration 50 complete: graph tables created');
  },

  // Version 51: chat session persistence + published conversations
  // chat_sessions / chat_messages: optional conversation_id thread persistence
  //   (Task #8) — POST /api/v1/chat accepts ?conversation_id=… and replays
  //   prior history. tenant_id is derived from the API key on first message.
  // published_conversations: REMOTE-mode save target (Task #9) — when a
  //   tenant calls POST /api/v1/chat/save with {domain, base_path}, the
  //   publish pipeline writes a row here keyed by (tenant_id, slug) and
  //   returns share_url+fetch_url. The remote site fetches by slug from
  //   GET /api/v1/conversations/{slug}?tenant=… (Task #10).
  51: async () => {
    logger.info('Starting migration 51: chat sessions + published conversations');

    await query(`
      CREATE TABLE IF NOT EXISTS chat_sessions (
        id TEXT PRIMARY KEY,                 -- conversation_id, e.g. "conv_<uuid>"
        tenant_id TEXT NOT NULL,             -- derived from API key (or "siftersearch" for internal)
        user_id INTEGER,                     -- nullable: anonymous chats are fine
        title TEXT,                          -- generated lazily from round 1 once rounds >= 2
        started_at TEXT DEFAULT CURRENT_TIMESTAMP,
        last_activity TEXT DEFAULT CURRENT_TIMESTAMP,
        message_count INTEGER DEFAULT 0,
        status TEXT DEFAULT 'active',        -- active | published | archived | deleted
        published_slug TEXT,                 -- set when this session is published via /save
        metadata_json TEXT                   -- {hero_image, topic, tags, keywords, …}
      )
    `);
    await query('CREATE INDEX IF NOT EXISTS idx_chat_sessions_tenant ON chat_sessions(tenant_id)');
    await query('CREATE INDEX IF NOT EXISTS idx_chat_sessions_user ON chat_sessions(user_id)');
    await query('CREATE INDEX IF NOT EXISTS idx_chat_sessions_last_activity ON chat_sessions(last_activity)');

    await query(`
      CREATE TABLE IF NOT EXISTS chat_messages (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        session_id TEXT NOT NULL,
        round_index INTEGER NOT NULL,        -- 0-based round number; user+assistant share the same round
        role TEXT NOT NULL,                  -- user | assistant | system | tool
        content TEXT NOT NULL,
        tool_calls_json TEXT,                -- for assistant messages with tool_calls
        tool_name TEXT,                      -- for tool result messages
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (session_id) REFERENCES chat_sessions(id) ON DELETE CASCADE
      )
    `);
    await query('CREATE INDEX IF NOT EXISTS idx_chat_messages_session ON chat_messages(session_id, round_index)');

    await query(`
      CREATE TABLE IF NOT EXISTS published_conversations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        tenant_id TEXT NOT NULL,             -- derived from API key
        slug TEXT NOT NULL,                  -- generated from title; unique per tenant
        title TEXT NOT NULL,                 -- question form
        description TEXT NOT NULL,           -- answer-summary
        question TEXT NOT NULL,              -- the seed question (round 1 user content)
        topic TEXT,
        tags_json TEXT,                      -- JSON array
        keywords_json TEXT,                  -- JSON array
        excerpt TEXT,                        -- pull-quote for listing cards
        hero_image TEXT,                     -- URL (R2/CDN)
        rounds_json TEXT NOT NULL,           -- JSON: [{n, user, jafar, round_summary:{question,answer}}]
        domain TEXT,                         -- e.g. "oceanoflights.org"
        base_path TEXT,                      -- e.g. "/conversations/"
        share_url TEXT,                      -- generated full URL
        conversation_id TEXT,                -- chat_sessions.id if published from a tracked session
        published_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(tenant_id, slug)
      )
    `);
    await query('CREATE INDEX IF NOT EXISTS idx_pubconv_tenant_slug ON published_conversations(tenant_id, slug)');
    await query('CREATE INDEX IF NOT EXISTS idx_pubconv_published_at ON published_conversations(published_at)');

    logger.info('Migration 51 complete: chat_sessions, chat_messages, published_conversations');
  },

  // Version 52: HyPE thesis column + Anthropic batch enrichment tracking.
  // Adds a separate doctrinal-thesis field per paragraph (one-sentence
  // proposition stating what the paragraph teaches). For tier 1-7 docs
  // (Bahá'í primary doctrinal) this is generated by Sonnet 4.6 via the
  // Anthropic Messages Batches API; for tier 8-9 by local Qwen3.
  52: async () => {
    logger.info('Starting migration 52: HyPE thesis + Sonnet batch tracking');
    // try/catch idempotency rather than PRAGMA table_info — the query()
    // helper misclassifies PRAGMA as a write and runs it via stmt.run()
    // which doesn't return row data, breaking column existence checks.
    try { await query('ALTER TABLE content ADD COLUMN hyp_thesis TEXT'); } catch (err) {
      if (!err.message?.includes('duplicate column')) throw err;
    }
    // Enrichment batch tracking — one row per Anthropic Messages Batches submission.
    // Records request → batch_id → status → completed_at, so the API enrichment
    // worker can resume across restarts and we can audit cost.
    await query(`
      CREATE TABLE IF NOT EXISTS enrichment_batches (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        provider TEXT NOT NULL,           -- 'anthropic'
        model TEXT NOT NULL,              -- 'claude-sonnet-4-6'
        external_batch_id TEXT,           -- provider's batch ID
        status TEXT NOT NULL DEFAULT 'pending',
                                          -- pending | submitted | in_progress | succeeded | failed | cancelled
        request_count INTEGER NOT NULL DEFAULT 0,
        succeeded_count INTEGER DEFAULT 0,
        failed_count INTEGER DEFAULT 0,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        submitted_at TEXT,
        completed_at TEXT,
        cost_input_tokens INTEGER DEFAULT 0,
        cost_output_tokens INTEGER DEFAULT 0,
        notes TEXT
      )
    `);
    await query('CREATE INDEX IF NOT EXISTS idx_enrichment_batches_status ON enrichment_batches(status)');

    // Pending paragraphs awaiting batch submission (queue between detection
    // and the next batch flush). Cleared once paragraphs are written into a
    // submitted batch.
    await query(`
      CREATE TABLE IF NOT EXISTS enrichment_pending (
        content_id INTEGER PRIMARY KEY,
        tier INTEGER NOT NULL,
        queued_at TEXT DEFAULT CURRENT_TIMESTAMP,
        batch_id INTEGER,                 -- FK enrichment_batches.id once assigned
        FOREIGN KEY (content_id) REFERENCES content(id),
        FOREIGN KEY (batch_id) REFERENCES enrichment_batches(id)
      )
    `);
    await query('CREATE INDEX IF NOT EXISTS idx_enrichment_pending_unassigned ON enrichment_pending(tier) WHERE batch_id IS NULL');
    await query('CREATE INDEX IF NOT EXISTS idx_enrichment_pending_batch ON enrichment_pending(batch_id) WHERE batch_id IS NOT NULL');

    // Index to find paragraphs needing enrichment per tier
    try { await query('CREATE INDEX IF NOT EXISTS idx_content_needs_thesis ON content(id) WHERE hyp_thesis IS NULL AND deleted_at IS NULL'); } catch { /* exists */ }

    logger.info('Migration 52 complete: hyp_thesis column + enrichment_batches/_pending tables');
  },

  // Version 53: Editable site content in DB. Replaces .astro source-of-truth
  // for docs and conversations with a `doc_pages` table + extends
  // `published_conversations` for in-place editing. Live Content Collections
  // (Astro 5 experimental, Astro 6 stable) fetch from our admin API at
  // request time, so editing a doc in DB → live without code deploy.
  53: async () => {
    logger.info('Starting migration 53: editable doc_pages + conversation body');

    await query(`
      CREATE TABLE IF NOT EXISTS doc_pages (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        slug TEXT UNIQUE NOT NULL,            -- "indexing-layers", "research-strategy"
        section TEXT,                          -- "research" | "agents" | "api" (nav grouping)
        nav_label TEXT,                        -- short sidebar label (defaults to title)
        sort_order INTEGER DEFAULT 100,
        title TEXT NOT NULL,
        description TEXT,                      -- meta description / social preview
        body_md TEXT NOT NULL,                 -- markdown source — the editable artifact
        body_html TEXT,                        -- pre-rendered HTML cache (regenerate on update)
        layout TEXT DEFAULT 'docs',            -- which Astro layout wraps it
        status TEXT DEFAULT 'published',       -- draft | published | archived
        active_section TEXT,                   -- DocsLayout's activeSection slug (defaults to slug)
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_by INTEGER                     -- nullable; references users(id) when known
      )
    `);
    await query('CREATE UNIQUE INDEX IF NOT EXISTS idx_doc_pages_slug ON doc_pages(slug)');
    await query('CREATE INDEX IF NOT EXISTS idx_doc_pages_section_sort ON doc_pages(section, sort_order)');
    await query('CREATE INDEX IF NOT EXISTS idx_doc_pages_status ON doc_pages(status)');

    // Extend published_conversations so the body itself is editable post-publish.
    // Existing rows already store rounds_json; we add markdown-source fields so an
    // editor can adjust per-round prose without re-running the LLM pipeline.
    // Same try/catch pattern as content columns above.
    try { await query('ALTER TABLE published_conversations ADD COLUMN body_md TEXT'); } catch (err) {
      if (!err.message?.includes('duplicate column')) throw err;
    }
    try { await query('ALTER TABLE published_conversations ADD COLUMN body_html TEXT'); } catch (err) {
      if (!err.message?.includes('duplicate column')) throw err;
    }
    try { await query("ALTER TABLE published_conversations ADD COLUMN status TEXT DEFAULT 'published'"); } catch (err) {
      if (!err.message?.includes('duplicate column')) throw err;
    }

    logger.info('Migration 53 complete: doc_pages + editable conversation body');
  },

  // Version 54: Translation pairing.
  //
  // Adds docs.original_doc_id — for translated documents, points to the
  // original-language doc in our own corpus when we have it. NULL otherwise
  // (which is most non-Bahá'í-primary cases). Used by the document subagent
  // and the translation subagent to fetch original alongside translation
  // when a user asks for both, or to ground LLM translation in the historical
  // concordance for that work.
  //
  // Also adds a small translation_cache table for memoizing CTAI-grounded
  // translations by content hash. Translations are deterministic-enough that
  // repeated requests for the same passage should hit cache rather than
  // re-paying the LLM cost.
  54: async () => {
    logger.info('Starting migration 54: translation pairing + cache');
    try { await query('ALTER TABLE docs ADD COLUMN original_doc_id INTEGER'); } catch (err) {
      if (!err.message?.includes('duplicate column')) throw err;
    }
    try { await query('CREATE INDEX IF NOT EXISTS idx_docs_original_doc_id ON docs(original_doc_id) WHERE original_doc_id IS NOT NULL'); } catch { /* exists */ }

    await query(`
      CREATE TABLE IF NOT EXISTS translation_cache (
        text_hash TEXT PRIMARY KEY,         -- sha256 of source text
        source_lang TEXT NOT NULL,           -- 'ar' | 'fa' | 'he' | etc.
        target_lang TEXT NOT NULL DEFAULT 'en',
        source_text TEXT NOT NULL,
        translation TEXT NOT NULL,
        jafar_terms_json TEXT,               -- the JAFAR analysis used to ground this
        model TEXT,                          -- which LLM produced the translation
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
      )
    `);
    await query('CREATE INDEX IF NOT EXISTS idx_translation_cache_lang ON translation_cache(source_lang, target_lang)');

    logger.info('Migration 54 complete: original_doc_id + translation_cache');
  },

  // Version 55: per-paragraph is_duplicate flag.
  //
  // Near-term primitive for sites integration — when content from an external
  // source duplicates material we already have, we mark the duplicate copy
  // rather than build full merge logic. Marked paragraphs are skipped by
  // Meili sync, HyPE enrichment, and default API queries.
  //
  // Set manually or by a one-shot dedup script. A future "prune" job can
  // hard-delete rows where is_duplicate = 1. See docs/sites-integration.md
  // for the eventual full duplicate-resolution architecture.
  55: async () => {
    logger.info('Starting migration 55: content.is_duplicate flag');
    try { await query('ALTER TABLE content ADD COLUMN is_duplicate INTEGER DEFAULT 0'); } catch (err) {
      if (!err.message?.includes('duplicate column')) throw err;
    }
    try { await query('CREATE INDEX IF NOT EXISTS idx_content_not_duplicate ON content(is_duplicate) WHERE is_duplicate = 0 AND deleted_at IS NULL'); } catch { /* exists */ }
    logger.info('Migration 55 complete: is_duplicate column added');
  },

  56: async () => {
    // External-site integration columns (OceanLibrary, etc.)
    //
    // docs.source_site         — provenance: 'oceanlibrary.com', NULL for ours
    // docs.source_url          — canonical URL at the source site (used to build
    //                            paragraph-level deep links: source_url/?paraId=NN)
    // docs.duplicate_of        — FK to docs.id; when set, this doc is superseded
    //                            by another (set on OUR copy when an OceanLibrary
    //                            version supersedes it). NULL = primary.
    // content.external_para_id — per-paragraph external ID (e.g. 'para_13' from
    //                            OceanLibrary's Pandoc attr blocks). NULL for ours.
    logger.info('Starting migration 56: external site integration columns');

    const addColumn = async (sql, label) => {
      try { await query(sql); logger.info({ label }, 'migration 56: column added'); }
      catch (err) {
        if (err.message?.includes('duplicate column')) return;
        throw err;
      }
    };

    await addColumn('ALTER TABLE docs ADD COLUMN source_site TEXT', 'docs.source_site');
    await addColumn('ALTER TABLE docs ADD COLUMN source_url TEXT', 'docs.source_url');
    await addColumn('ALTER TABLE docs ADD COLUMN duplicate_of INTEGER REFERENCES docs(id)', 'docs.duplicate_of');
    await addColumn('ALTER TABLE content ADD COLUMN external_para_id TEXT', 'content.external_para_id');

    // Indexes
    // - source_site lookup: "all OceanLibrary docs"
    // - duplicate_of lookup: "what supersedes this?" + "what does this supersede?"
    // - external_para_id is per-doc-scoped; only index it within a doc since
    //   OceanLibrary's `para_NN` ids restart at 1 in every book.
    try { await query('CREATE INDEX IF NOT EXISTS idx_docs_source_site ON docs(source_site) WHERE source_site IS NOT NULL'); } catch { /* exists */ }
    try { await query('CREATE INDEX IF NOT EXISTS idx_docs_duplicate_of ON docs(duplicate_of) WHERE duplicate_of IS NOT NULL'); } catch { /* exists */ }
    try { await query('CREATE INDEX IF NOT EXISTS idx_content_external_para ON content(doc_id, external_para_id) WHERE external_para_id IS NOT NULL'); } catch { /* exists */ }

    logger.info('Migration 56 complete: external site columns + indexes');
  },

  57: async () => {
    // External-source canonical ID on docs. The OceanLibrary adapter writes
    // the OL `bookid` here; future adapters use the same column. Distinct
    // from `external_para_id` on content (per-paragraph IDs).
    logger.info('Starting migration 57: docs.external_id');
    try { await query('ALTER TABLE docs ADD COLUMN external_id TEXT'); } catch (err) {
      if (!err.message?.includes('duplicate column')) throw err;
    }
    try { await query('CREATE INDEX IF NOT EXISTS idx_docs_external_id ON docs(external_id) WHERE external_id IS NOT NULL'); } catch { /* exists */ }
    logger.info('Migration 57 complete: docs.external_id added');
  },

  58: async () => {
    // Supersession-lookup covering index.
    //
    // The existing idx_content_normalized_hash is partial on `embedding IS NOT
    // NULL`, which doesn't match supersession queries (we don't filter on
    // embedding). When the supersession query runs, SQLite picks
    // idx_content_deleted_at instead — a column that's NULL for ~99% of rows
    // and is therefore useless as a discriminator. Result: full content scan,
    // 50+ seconds per query.
    //
    // This index covers (normalized_hash, doc_id) WHERE deleted_at IS NULL,
    // which is exactly what `findSupersessionCandidates` queries. Includes
    // doc_id so the query can be answered without table access.
    logger.info('Starting migration 58: supersession-lookup covering index');
    try {
      await query(`
        CREATE INDEX IF NOT EXISTS idx_content_norm_active
        ON content(normalized_hash, doc_id)
        WHERE deleted_at IS NULL
      `);
    } catch (err) { logger.warn({ err: err.message }, 'idx_content_norm_active create skipped'); }
    logger.info('Migration 58 complete: idx_content_norm_active created');
  },

  59: async () => {
    // HyPE sync queue partial index.
    //
    // syncHypeBatch (api/lib/search/hype.js) pulls paragraphs that have been
    // enriched (hyp_questions or hyp_thesis populated) but not yet synced to
    // the HyPE sidecar Meili index. With 4M+ rows in content and 99% having
    // deleted_at IS NULL, the planner was picking idx_content_deleted_at and
    // scanning the whole table — 54s per batch — driving worker into a death
    // spiral against the PM2 memory cap. This partial index matches the exact
    // WHERE clause and lets the batch return in <200ms.
    //
    // The query in hype.js uses INDEXED BY to force the planner onto this
    // index even after table stats change.
    logger.info('Starting migration 59: HyPE sync queue partial index');
    try {
      await query(`
        CREATE INDEX IF NOT EXISTS idx_content_hype_to_sync
        ON content(id)
        WHERE enhanced_synced = 0
          AND deleted_at IS NULL
          AND (hyp_questions IS NOT NULL OR hyp_thesis IS NOT NULL)
          AND COALESCE(is_duplicate, 0) = 0
      `);
    } catch (err) { logger.warn({ err: err.message }, 'idx_content_hype_to_sync create skipped'); }
    logger.info('Migration 59 complete: idx_content_hype_to_sync created');
  },

  60: async () => {
    // Three-class scope model for external-site content.
    //
    // docs.scope ∈ {'primary', 'supplemental', 'site-only'} controls which
    // search code paths can see the row:
    //   - 'primary'      → curated corpus, default Jafar
    //   - 'supplemental' → external sites visible in default Jafar at low authority
    //   - 'site-only'    → never appears in default Jafar (its content lives in a
    //                      separate per-site SQLite under data/sites/<prefix>.db,
    //                      so this column value won't appear in main DB; reserved
    //                      for completeness)
    //
    // Backfill rule: existing rows with source_site IS NOT NULL are
    // 'supplemental' (currently just oceanlibrary.com); everything else is
    // 'primary'.
    //
    // Also adds content.pdf_page — for PDF-derived crawler MD, the source PDF
    // page number per paragraph. Combined with docs.source_url at search time
    // to build deeplinks like `<source_url>#page=<pdf_page>`. NULL for
    // HTML-derived content.
    //
    // Indexes added: idx_docs_scope, idx_docs_source_site (filter speed for
    // scope-aware search), idx_content_is_duplicate (filter speed for the
    // sync worker which must skip duplicates).
    logger.info('Starting migration 60: docs.scope, content.pdf_page, scope/source_site indexes');
    try {
      await query(`ALTER TABLE docs ADD COLUMN scope TEXT NOT NULL DEFAULT 'primary'`);
    } catch (err) {
      if (!err.message?.includes('duplicate column')) throw err;
    }
    try {
      await query(`ALTER TABLE content ADD COLUMN pdf_page INTEGER`);
    } catch (err) {
      if (!err.message?.includes('duplicate column')) throw err;
    }
    await query(`UPDATE docs SET scope = 'supplemental' WHERE source_site IS NOT NULL AND scope = 'primary'`);

    try { await query('CREATE INDEX IF NOT EXISTS idx_docs_scope ON docs(scope) WHERE deleted_at IS NULL'); } catch { /* exists */ }
    try { await query('CREATE INDEX IF NOT EXISTS idx_docs_source_site ON docs(source_site) WHERE source_site IS NOT NULL'); } catch { /* exists */ }
    try { await query('CREATE INDEX IF NOT EXISTS idx_content_is_duplicate ON content(is_duplicate) WHERE is_duplicate = 1'); } catch { /* exists */ }

    // ANALYZE so the planner picks up the new indexes immediately. Same
    // pattern as migration 58. Skip on test DBs (in-memory) where ANALYZE
    // is a no-op anyway.
    try { await query('ANALYZE docs'); } catch { /* skip */ }
    try { await query('ANALYZE content'); } catch { /* skip */ }

    logger.info('Migration 60 complete: scope + pdf_page columns + indexes added');
  },

  61: async () => {
    // Add block_attrs TEXT to content — stores the full set of hugo-style block
    // attributes ({pdf_page=42 .class #id key="value"}) as a JSON object.
    // pdf_page is already its own column; block_attrs preserves everything else
    // for future use (e.g. anchor IDs, CSS classes, custom keys from PDF pipeline).
    logger.info('Starting migration 61: content.block_attrs');
    try {
      await query(`ALTER TABLE content ADD COLUMN block_attrs TEXT`);
    } catch (err) {
      if (!err.message?.includes('duplicate column')) throw err;
    }
    logger.info('Migration 61 complete: content.block_attrs added');
  },

  62: async () => {
    // Extend published_conversations to support the full dialog schema:
    // score, featured, hero_prompt, round_titles_json, assessment_json,
    // rounds_count. These fields are set by the batch-runner and admin API;
    // the Astro dialog pages read them instead of markdown frontmatter,
    // making dialogs live-editable without rebuilds.
    logger.info('Starting migration 62: published_conversations dialog fields');
    const addCol = async (sql) => {
      try { await query(sql); }
      catch (err) { if (!err.message?.includes('duplicate column')) throw err; }
    };
    await addCol('ALTER TABLE published_conversations ADD COLUMN score INTEGER DEFAULT 0');
    await addCol('ALTER TABLE published_conversations ADD COLUMN featured INTEGER DEFAULT 0');
    await addCol('ALTER TABLE published_conversations ADD COLUMN hero_prompt TEXT');
    await addCol('ALTER TABLE published_conversations ADD COLUMN round_titles_json TEXT');
    await addCol('ALTER TABLE published_conversations ADD COLUMN assessment_json TEXT');
    await addCol('ALTER TABLE published_conversations ADD COLUMN rounds_count INTEGER DEFAULT 0');
    try { await query('CREATE INDEX IF NOT EXISTS idx_pubconv_tenant_status_score ON published_conversations(tenant_id, status, score DESC)'); } catch { /* exists */ }
    try { await query('CREATE INDEX IF NOT EXISTS idx_pubconv_tenant_featured ON published_conversations(tenant_id, featured) WHERE featured = 1'); } catch { /* exists */ }
    try { await query('CREATE INDEX IF NOT EXISTS idx_pubconv_tenant_topic ON published_conversations(tenant_id, topic)'); } catch { /* exists */ }
    logger.info('Migration 62 complete: dialog fields added to published_conversations');
  },

  63: async () => {
    // Backfill docs.religion for supplemental site docs where religion is NULL.
    //
    // The site2rag adapter historically set religion=NULL for all crawler-derived
    // docs. These sites are single-religion (Bahá'í), so NULL causes two problems:
    //   1. Authority lookups fall through to global default (5) instead of using
    //      religion-based authority from library meta.yaml.
    //   2. They add invisible volume to cross-tradition result pollution.
    //
    // Known mappings:
    //   bahai-library.com   → Baha'i
    //   oceanoflights.org   → Baha'i
    //   bahaiteachings.org  → Baha'i (site-only, separate DB, but safe to set)
    //
    // Ocean Library (oceanlibrary.com) already sets religion from ocean_category
    // frontmatter via religion_map — only docs WITHOUT a mapped category land as
    // NULL there. Those are set to 'General' by the adapter already; this
    // migration leaves OL docs alone.
    //
    // The site2rag adapter now reads siteConfig.default_religion at parse time;
    // this migration backfills the existing data.
    logger.info('Starting migration 63: backfill religion for supplemental site docs');
    const siteReligions = [
      ['bahai-library.com', "Baha'i"],
      ['oceanoflights.org', "Baha'i"],
      ['bahaiteachings.org', "Baha'i"],
    ];
    for (const [site, religion] of siteReligions) {
      const { count } = await queryOne(
        'SELECT COUNT(*) as count FROM docs WHERE source_site = ? AND religion IS NULL',
        [site]
      );
      if (count > 0) {
        await query(
          'UPDATE docs SET religion = ? WHERE source_site = ? AND religion IS NULL',
          [religion, site]
        );
        logger.info({ site, religion, count }, 'Migration 63: backfilled religion');
      }
    }
    logger.info('Migration 63 complete: supplemental site religion backfill done');
  },

  64: async () => {
    // Topic tagging columns + Deep Research tables.
    //
    // Topic tagging (content table):
    //   topic_tags       — JSON array of primary/secondary topic labels e.g. ["theodicy","tests-trials"]
    //   question_types   — JSON array of question-type labels e.g. ["why-god-allows-X"]
    //   topic_tagged_at  — ISO timestamp of last AI tagging run
    //
    // Deep Research tables:
    //   deep_research        — one row per canonical question with status + metadata
    //   deep_research_quotes — curated passage set per research record
    //   deep_research_queue  — lightweight job queue for async research tasks
    logger.info('Starting migration 64: topic tagging columns + deep research tables');
    const addCol = async (sql) => {
      try { await query(sql); }
      catch (err) { if (!err.message?.includes('duplicate column')) throw err; }
    };

    // Topic tagging on content paragraphs
    await addCol('ALTER TABLE content ADD COLUMN topic_tags TEXT');
    await addCol('ALTER TABLE content ADD COLUMN question_types TEXT');
    await addCol('ALTER TABLE content ADD COLUMN topic_tagged_at TEXT');
    try {
      await query(`CREATE INDEX IF NOT EXISTS idx_content_topic_tags ON content(doc_id) WHERE topic_tags IS NOT NULL`);
    } catch { /* exists */ }

    // Deep research master table
    await query(`
      CREATE TABLE IF NOT EXISTS deep_research (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        canonical_question TEXT NOT NULL,
        question_embedding BLOB,
        question_hash TEXT NOT NULL UNIQUE,
        status TEXT NOT NULL DEFAULT 'pending',
        priority INTEGER NOT NULL DEFAULT 5,
        topic_tags TEXT,
        question_type TEXT,
        traditions_covered TEXT,
        angles_json TEXT,
        total_candidates INTEGER DEFAULT 0,
        total_selected INTEGER DEFAULT 0,
        research_model TEXT,
        rerank_model TEXT,
        ask_count INTEGER DEFAULT 0,
        last_asked_at TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        completed_at TEXT,
        reviewed_at TEXT,
        reviewed_by TEXT,
        worker_id TEXT,
        heartbeat_at TEXT,
        error TEXT
      )
    `);
    try { await query('CREATE INDEX IF NOT EXISTS idx_dr_status ON deep_research(status, priority DESC)'); } catch { /* exists */ }
    try { await query('CREATE INDEX IF NOT EXISTS idx_dr_hash ON deep_research(question_hash)'); } catch { /* exists */ }
    try { await query('CREATE INDEX IF NOT EXISTS idx_dr_ask_count ON deep_research(ask_count DESC)'); } catch { /* exists */ }

    // Curated quotes for each research record
    await query(`
      CREATE TABLE IF NOT EXISTS deep_research_quotes (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        research_id INTEGER NOT NULL REFERENCES deep_research(id) ON DELETE CASCADE,
        para_id INTEGER NOT NULL REFERENCES content(id),
        tradition TEXT,
        authority INTEGER,
        relevance_score REAL,
        contextual_note TEXT,
        rank INTEGER,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
      )
    `);
    try { await query('CREATE INDEX IF NOT EXISTS idx_drq_research ON deep_research_quotes(research_id, rank)'); } catch { /* exists */ }
    try { await query('CREATE INDEX IF NOT EXISTS idx_drq_para ON deep_research_quotes(para_id)'); } catch { /* exists */ }

    // Async job queue for research tasks
    await query(`
      CREATE TABLE IF NOT EXISTS deep_research_queue (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        research_id INTEGER NOT NULL REFERENCES deep_research(id) ON DELETE CASCADE,
        job_type TEXT NOT NULL DEFAULT 'research',
        status TEXT NOT NULL DEFAULT 'pending',
        attempts INTEGER DEFAULT 0,
        priority INTEGER NOT NULL DEFAULT 5,
        payload TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        started_at TEXT,
        completed_at TEXT,
        error TEXT
      )
    `);
    try { await query('CREATE INDEX IF NOT EXISTS idx_drqueue_status ON deep_research_queue(status, priority DESC)'); } catch { /* exists */ }

    logger.info('Migration 64 complete: topic tagging columns + deep research tables added');
  },

  65: async () => {
    // Marker: deep_research Meilisearch index.
    // No SQL changes — this version signals api/lib/search.js initializeIndexes()
    // to create the deep_research index with filterable attributes:
    //   topic_tags, question_type, traditions_covered, status, ask_count, priority
    // and to add topic_tags + question_types to the paragraphs index filterableAttributes.
    // The actual Meili calls happen in initializeIndexes() keyed off CURRENT_VERSION >= 65.
    logger.info('Migration 65 complete: deep_research Meilisearch index marker');
  },

  66: async () => {
    // Add slug + AI-generated summary fields to deep_research;
    // add email notification table for "notify me when done" capture.
    logger.info('Starting migration 66: deep_research slug + summary + notify table');
    const addCol = async (sql) => {
      try { await query(sql); }
      catch (err) { if (!err.message?.includes('duplicate column')) throw err; }
    };
    await addCol('ALTER TABLE deep_research ADD COLUMN slug TEXT');
    // sections_json: JSON array of {type, title, content, topic_tags, tradition, relevance_score}
    // Indexes the full editorial content — summaries, per-tradition analysis, convergence —
    // as structured data so it can be synced to Meilisearch with pre-gauged relevancy.
    await addCol('ALTER TABLE deep_research ADD COLUMN sections_json TEXT');
    // summary_json: {text, key_points[]} — executive summary of findings
    await addCol('ALTER TABLE deep_research ADD COLUMN summary_json TEXT');
    // convergence_json: {agreements[], divergences[], unique_perspectives[]}
    await addCol('ALTER TABLE deep_research ADD COLUMN convergence_json TEXT');
    // qa_json: [{question, answer, traditions_cited[]}] — FAQ pairs for Schema.org/SEO
    await addCol('ALTER TABLE deep_research ADD COLUMN qa_json TEXT');
    try { await query('CREATE UNIQUE INDEX IF NOT EXISTS idx_dr_slug ON deep_research(slug) WHERE slug IS NOT NULL'); } catch { /* exists */ }

    await query(`
      CREATE TABLE IF NOT EXISTS deep_research_notify (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        research_id INTEGER NOT NULL REFERENCES deep_research(id) ON DELETE CASCADE,
        email TEXT NOT NULL,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        notified_at TEXT,
        UNIQUE(research_id, email)
      )
    `);
    try { await query('CREATE INDEX IF NOT EXISTS idx_drn_research ON deep_research_notify(research_id)'); } catch { /* exists */ }
    try { await query('CREATE INDEX IF NOT EXISTS idx_drn_pending ON deep_research_notify(notified_at) WHERE notified_at IS NULL'); } catch { /* exists */ }
    logger.info('Migration 66 complete: slug + summary + notify table added');
  },

  // para_meta: structured per-paragraph metadata — authorship attribution for
  // compilations (and other block-level context). Populated by the attribution
  // enrichment pass; null means not yet processed. is_attribution_line flags
  // pure citation-source paragraphs that should be suppressed from search.
  67: async () => {
    const addCol = async (sql) => {
      try { await query(sql); } catch (err) { if (!err.message?.includes('duplicate column')) throw err; }
    };
    await addCol('ALTER TABLE content ADD COLUMN para_meta TEXT');
    await addCol('ALTER TABLE content ADD COLUMN para_meta_model TEXT');
    try {
      await query('CREATE INDEX IF NOT EXISTS idx_content_attribution_line ON content(doc_id) WHERE json_extract(para_meta, \'$.is_attribution_line\') = 1');
    } catch { /* exists or json_extract not supported */ }
    try {
      await query('CREATE INDEX IF NOT EXISTS idx_content_para_meta_null ON content(doc_id, id) WHERE para_meta IS NULL AND deleted_at IS NULL');
    } catch { /* exists */ }
    logger.info('Migration 67 complete: para_meta attribution column added');
  },

  68: async () => {
    const addCol = async (sql) => {
      try { await query(sql); } catch (err) { if (!err.message?.includes('duplicate column')) throw err; }
    };
    // LLM cost tracking for deep research runs: total tokens + estimated USD per research job.
    // Per-step breakdown stored in cost_breakdown_json for optimization analysis.
    await addCol('ALTER TABLE deep_research ADD COLUMN llm_input_tokens INTEGER DEFAULT 0');
    await addCol('ALTER TABLE deep_research ADD COLUMN llm_output_tokens INTEGER DEFAULT 0');
    await addCol('ALTER TABLE deep_research ADD COLUMN llm_cost_usd REAL DEFAULT 0');
    await addCol('ALTER TABLE deep_research ADD COLUMN cost_breakdown_json TEXT');
    logger.info('Migration 68 complete: deep_research cost tracking columns added');
  },

  69: async () => {
    // ai_usage table was referenced throughout ai-services.js and admin routes but
    // never created in a migration — every logAIUsage() call silently failed.
    await query(`
      CREATE TABLE IF NOT EXISTS ai_usage (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        timestamp TEXT DEFAULT (datetime('now')),
        provider TEXT NOT NULL,
        model TEXT NOT NULL,
        service_type TEXT,
        prompt_tokens INTEGER DEFAULT 0,
        completion_tokens INTEGER DEFAULT 0,
        total_tokens INTEGER DEFAULT 0,
        estimated_cost_usd REAL DEFAULT 0,
        caller TEXT,
        success INTEGER DEFAULT 1,
        error_message TEXT,
        user_id TEXT,
        job_id TEXT,
        document_id TEXT
      )
    `);
    try { await query('CREATE INDEX IF NOT EXISTS idx_ai_usage_timestamp ON ai_usage(timestamp DESC)'); } catch { /* exists */ }
    try { await query('CREATE INDEX IF NOT EXISTS idx_ai_usage_caller ON ai_usage(caller, timestamp DESC)'); } catch { /* exists */ }
    try { await query('CREATE INDEX IF NOT EXISTS idx_ai_usage_model ON ai_usage(model, timestamp DESC)'); } catch { /* exists */ }
    logger.info('Migration 69 complete: ai_usage table created');
  },
};
